W.grade7=[
{"w": "apple", "p": "/ˈæpl/", "z": "n. 苹果", "e": "She ate a red apple."},
{"w": "banana", "p": "/bəˈnɑːnə/", "z": "n. 香蕉", "e": "Monkeys like bananas."},
{"w": "orange", "p": "/ˈɒrɪndʒ/", "z": "n. 橙子", "e": "Orange juice is fresh."},
{"w": "grape", "p": "/ɡreɪp/", "z": "n. 葡萄", "e": "A bunch of grapes."},
{"w": "pear", "p": "/peə/", "z": "n. 梨", "e": "The pear is sweet."},
{"w": "watermelon", "p": "/ˈwɔːtəmelən/", "z": "n. 西瓜", "e": "Eat watermelon in summer."},
{"w": "strawberry", "p": "/ˈstrɔːbəri/", "z": "n. 草莓", "e": "Strawberry is my favorite."},
{"w": "red", "p": "/red/", "z": "adj. 红色的", "e": "A red dress."},
{"w": "blue", "p": "/bluː/", "z": "adj. 蓝色的", "e": "Blue sky."},
{"w": "green", "p": "/ɡriːn/", "z": "adj. 绿色的", "e": "Green grass."},
{"w": "yellow", "p": "/ˈjeləʊ/", "z": "adj. 黄色的", "e": "Yellow sunflowers."},
{"w": "white", "p": "/waɪt/", "z": "adj. 白色的", "e": "A white shirt."},
{"w": "black", "p": "/blæk/", "z": "adj. 黑色的", "e": "A black cat."},
{"w": "pink", "p": "/pɪŋk/", "z": "adj. 粉色的", "e": "Pink flowers."},
{"w": "mother", "p": "/ˈmʌðə/", "z": "n. 母亲", "e": "My mother cooks well."},
{"w": "father", "p": "/ˈfɑːðə/", "z": "n. 父亲", "e": "My father drives."},
{"w": "sister", "p": "/ˈsɪstə/", "z": "n. 姐妹", "e": "My sister is older."},
{"w": "brother", "p": "/ˈbrʌðə/", "z": "n. 兄弟", "e": "My brother plays football."},
{"w": "family", "p": "/ˈfæməli/", "z": "n. 家庭", "e": "I love my family."},
{"w": "friend", "p": "/frend/", "z": "n. 朋友", "e": "She is my best friend."},
{"w": "teacher", "p": "/ˈtiːtʃə/", "z": "n. 老师", "e": "Our teacher is kind."},
{"w": "student", "p": "/ˈstjuːdənt/", "z": "n. 学生", "e": "Forty students."},
{"w": "school", "p": "/skuːl/", "z": "n. 学校", "e": "Go to school."},
{"w": "classroom", "p": "/ˈklɑːsruːm/", "z": "n. 教室", "e": "Clean classroom."},
{"w": "library", "p": "/ˈlaɪbrəri/", "z": "n. 图书馆", "e": "Read in the library."},
{"w": "playground", "p": "/ˈpleɪɡraʊnd/", "z": "n. 操场", "e": "Kids on the playground."},
{"w": "book", "p": "/bʊk/", "z": "n. 书", "e": "Borrow a book."},
{"w": "pencil", "p": "/ˈpensl/", "z": "n. 铅笔", "e": "Borrow a pencil."},
{"w": "notebook", "p": "/ˈnəʊtbʊk/", "z": "n. 笔记本", "e": "Write in your notebook."},
{"w": "bag", "p": "/bæɡ/", "z": "n. 书包", "e": "My bag is heavy."},
{"w": "desk", "p": "/desk/", "z": "n. 书桌", "e": "A lamp on the desk."},
{"w": "chair", "p": "/tʃeə/", "z": "n. 椅子", "e": "Take a seat."},
{"w": "rice", "p": "/raɪs/", "z": "n. 米饭", "e": "Eat rice for dinner."},
{"w": "bread", "p": "/bred/", "z": "n. 面包", "e": "Bread and milk."},
{"w": "milk", "p": "/mɪlk/", "z": "n. 牛奶", "e": "Milk for bones."},
{"w": "water", "p": "/ˈwɔːtə/", "z": "n. 水", "e": "Drink water."},
{"w": "chicken", "p": "/ˈtʃɪkɪn/", "z": "n. 鸡肉", "e": "Fried chicken."},
{"w": "fish", "p": "/fɪʃ/", "z": "n. 鱼", "e": "Fish for dinner."},
{"w": "egg", "p": "/eɡ/", "z": "n. 鸡蛋", "e": "Two eggs."},
{"w": "dog", "p": "/dɒɡ/", "z": "n. 狗", "e": "The dog plays."},
{"w": "cat", "p": "/kæt/", "z": "n. 猫", "e": "The cat sleeps."},
{"w": "bird", "p": "/bɜːd/", "z": "n. 鸟", "e": "A bird sings."},
{"w": "rabbit", "p": "/ˈræbɪt/", "z": "n. 兔子", "e": "Long ears."},
{"w": "elephant", "p": "/ˈelɪfənt/", "z": "n. 大象", "e": "Large elephant."},
{"w": "monkey", "p": "/ˈmʌŋki/", "z": "n. 猴子", "e": "The monkey climbs."},
{"w": "panda", "p": "/ˈpændə/", "z": "n. 熊猫", "e": "A national treasure."},
{"w": "tiger", "p": "/ˈtaɪɡə/", "z": "n. 老虎", "e": "A wild tiger."},
{"w": "lion", "p": "/ˈlaɪən/", "z": "n. 狮子", "e": "King of animals."},
{"w": "head", "p": "/hed/", "z": "n. 头", "e": "Nod your head."},
{"w": "eye", "p": "/aɪ/", "z": "n. 眼睛", "e": "Blue eyes."},
{"w": "ear", "p": "/ɪə/", "z": "n. 耳朵", "e": "Long ears."},
{"w": "nose", "p": "/nəʊz/", "z": "n. 鼻子", "e": "Good nose."},
{"w": "mouth", "p": "/maʊθ/", "z": "n. 嘴巴", "e": "Open your mouth."},
{"w": "hand", "p": "/hænd/", "z": "n. 手", "e": "Raise your hand."},
{"w": "foot", "p": "/fʊt/", "z": "n. 脚", "e": "Hurt his foot."},
{"w": "morning", "p": "/ˈmɔːnɪŋ/", "z": "n. 早晨", "e": "Good morning!"},
{"w": "afternoon", "p": "/.ˌɑːftəˈnuːn/", "z": "n. 下午", "e": "PE in the afternoon."},
{"w": "evening", "p": "/ˈiːvnɪŋ/", "z": "n. 傍晚", "e": "Homework in the evening."},
{"w": "today", "p": "/təˈdeɪ/", "z": "n. 今天", "e": "Today is sunny."},
{"w": "tomorrow", "p": "/təˈmɒrəʊ/", "z": "n. 明天", "e": "Test tomorrow."},
{"w": "spring", "p": "/sprɪŋ/", "z": "n. 春天", "e": "Flowers in spring."},
{"w": "summer", "p": "/ˈsʌmə/", "z": "n. 夏天", "e": "Swim in summer."},
{"w": "autumn", "p": "/ˈɔːtəm/", "z": "n. 秋天", "e": "Leaves turn yellow."},
{"w": "winter", "p": "/ˈwɪntə/", "z": "n. 冬天", "e": "It snows."},
{"w": "happy", "p": "/ˈhæpi/", "z": "adj. 快乐的", "e": "Feel happy."},
{"w": "sad", "p": "/sæd/", "z": "adj. 伤心的", "e": "She looks sad."},
{"w": "big", "p": "/bɪɡ/", "z": "adj. 大的", "e": "A big tree."},
{"w": "small", "p": "/smɔːl/", "z": "adj. 小的", "e": "Small kitten."},
{"w": "long", "p": "/lɒŋ/", "z": "adj. 长的", "e": "Long river."},
{"w": "short", "p": "/ʃɔːt/", "z": "adj. 短的", "e": "Short but strong."},
{"w": "run", "p": "/rʌn/", "z": "v. 跑步", "e": "Love to run."},
{"w": "walk", "p": "/wɔːk/", "z": "v. 走路", "e": "Walk to school."},
{"w": "eat", "p": "/iːt/", "z": "v. 吃", "e": "Eat vegetables."},
{"w": "drink", "p": "/drɪŋk/", "z": "v. 喝", "e": "Drink water."},
{"w": "read", "p": "/riːd/", "z": "v. 阅读", "e": "I like to read."},
{"w": "write", "p": "/raɪt/", "z": "v. 写", "e": "Write your name."},
{"w": "sing", "p": "/sɪŋ/", "z": "v. 唱歌", "e": "She likes to sing."},
{"w": "dance", "p": "/dɑːns/", "z": "v. 跳舞", "e": "Girls dance."},
{"w": "swim", "p": "/swɪm/", "z": "v. 游泳", "e": "Learn to swim."},
{"w": "play", "p": "/pleɪ/", "z": "v. 玩", "e": "Play basketball."},
{"w": "love", "p": "/lʌv/", "z": "v./n. 爱", "e": "I love family."},
{"w": "like", "p": "/laɪk/", "z": "v. 喜欢", "e": "I like piano."},
{"w": "have", "p": "/hæv/", "z": "v. 有", "e": "A new bike."},
{"w": "go", "p": "/ɡəʊ/", "z": "v. 去", "e": "Go to the park."},
{"w": "come", "p": "/kʌm/", "z": "v. 来", "e": "Come to the party."},
];
