var AI_EXTRA = [
  {w:'accessibility',p:'/əkˌsesəˈbɪləti/',z:'n. 无障碍性',e:'Accessibility helps more people use the app.'},
  {w:'agent',p:'/ˈeɪdʒənt/',z:'n. 智能体；代理',e:'The agent can complete a simple task.'},
  {w:'automation',p:'/ˌɔːtəˈmeɪʃən/',z:'n. 自动化',e:'Automation saves time on routine work.'},
  {w:'avatar',p:'/ˈævətɑːr/',z:'n. 虚拟头像',e:'Choose an avatar for your profile.'},
  {w:'classification',p:'/ˌklæsɪfɪˈkeɪʃən/',z:'n. 分类',e:'Image classification needs labeled data.'},
  {w:'codebase',p:'/ˈkoʊdbeɪs/',z:'n. 代码库',e:'The team shares one codebase.'},
  {w:'coding',p:'/ˈkoʊdɪŋ/',z:'n. 编程',e:'Coding is a useful skill.'},
  {w:'command',p:'/kəˈmænd/',z:'n. 命令',e:'Type the command in the terminal.'},
  {w:'computer vision',p:'/kəmˈpjuːtər ˈvɪʒən/',z:'n. 计算机视觉',e:'Computer vision can identify objects.'},
  {w:'configuration',p:'/kənˌfɪɡəˈreɪʃən/',z:'n. 配置',e:'Save the configuration before you start.'},
  {w:'container',p:'/kənˈteɪnər/',z:'n. 容器',e:'The service runs in a container.'},
  {w:'crawler',p:'/ˈkrɔːlər/',z:'n. 爬虫',e:'A crawler collects pages for search.'},
  {w:'data pipeline',p:'/ˈdeɪtə ˈpaɪplaɪn/',z:'n. 数据管道',e:'The data pipeline runs every night.'},
  {w:'data privacy',p:'/ˈdeɪtə ˈpraɪvəsi/',z:'n. 数据隐私',e:'Data privacy is a basic responsibility.'},
  {w:'data science',p:'/ˈdeɪtə ˈsaɪəns/',z:'n. 数据科学',e:'Data science combines math and computing.'},
  {w:'data source',p:'/ˈdeɪtə sɔːrs/',z:'n. 数据来源',e:'Check the data source first.'},
  {w:'deep learning',p:'/diːp ˈlɜːrnɪŋ/',z:'n. 深度学习',e:'Deep learning uses many layers.'},
  {w:'developer',p:'/dɪˈveləpər/',z:'n. 开发者',e:'The developer fixed the issue.'},
  {w:'diffusion',p:'/dɪˈfjuːʒən/',z:'n. 扩散',e:'Diffusion models can create images.'},
  {w:'document',p:'/ˈdɑːkjəmənt/',z:'n. 文档',e:'Read the document before editing.'},
  {w:'embedding model',p:'/ɪmˈbedɪŋ ˈmɑːdl/',z:'n. 嵌入模型',e:'An embedding model compares meanings.'},
  {w:'evaluation',p:'/ɪˌvæljuˈeɪʃən/',z:'n. 评估',e:'Evaluation shows where the model fails.'},
  {w:'experiment',p:'/ɪkˈsperɪmənt/',z:'n. 实验',e:'Run one experiment at a time.'},
  {w:'face recognition',p:'/feɪs ˌrekəɡˈnɪʃən/',z:'n. 人脸识别',e:'Face recognition needs careful testing.'},
  {w:'fine tune',p:'/faɪn tuːn/',z:'v. 微调',e:'We fine tune the model with examples.'},
  {w:'function calling',p:'/ˈfʌŋkʃən ˈkɔːlɪŋ/',z:'n. 函数调用',e:'Function calling lets a model use tools.'},
  {w:'generative',p:'/ˈdʒenərətɪv/',z:'adj. 生成式的',e:'Generative tools can make new content.'},
  {w:'GPU',p:'/ˌdʒiː piː ˈjuː/',z:'n. 图形处理器',e:'A GPU speeds up model training.'},
  {w:'guardrail',p:'/ˈɡɑːrdreɪl/',z:'n. 安全护栏',e:'A guardrail limits unsafe behavior.'},
  {w:'image generation',p:'/ˈɪmɪdʒ ˌdʒenəˈreɪʃən/',z:'n. 图像生成',e:'Image generation starts with a prompt.'},
  {w:'jailbreak',p:'/ˈdʒeɪlbreɪk/',z:'n./v. 越狱；绕过限制',e:'The system should resist a jailbreak.'},
  {w:'knowledge base',p:'/ˈnɑːlɪdʒ beɪs/',z:'n. 知识库',e:'The assistant searches the knowledge base.'},
  {w:'label',p:'/ˈleɪbəl/',z:'n./v. 标签；标注',e:'Each image needs a correct label.'},
  {w:'machine learning',p:'/məˈʃiːn ˈlɜːrnɪŋ/',z:'n. 机器学习',e:'Machine learning finds patterns in data.'},
  {w:'multimodal',p:'/ˌmʌltiˈmoʊdəl/',z:'adj. 多模态的',e:'A multimodal model can read images.'},
  {w:'natural language',p:'/ˈnætʃərəl ˈlæŋɡwɪdʒ/',z:'n. 自然语言',e:'The model understands natural language.'},
  {w:'OCR',p:'/ˌoʊ siː ˈɑːr/',z:'n. 光学字符识别',e:'OCR turns a photo into editable text.'},
  {w:'parameter',p:'/pəˈræmətər/',z:'n. 参数',e:'The parameter changes the result.'},
  {w:'plug-in',p:'/ˈplʌɡ ɪn/',z:'n. 插件',e:'Install a plug-in for extra features.'},
  {w:'prediction',p:'/prɪˈdɪkʃən/',z:'n. 预测',e:'The prediction was close to the answer.'},
  {w:'preprocessing',p:'/ˌpriːˈprɑːsesɪŋ/',z:'n. 预处理',e:'Preprocessing removes noisy data.'},
  {w:'privacy',p:'/ˈpraɪvəsi/',z:'n. 隐私',e:'Privacy should be protected by design.'},
  {w:'public model',p:'/ˈpʌblɪk ˈmɑːdl/',z:'n. 公共模型',e:'The public model has clear documentation.'},
  {w:'prompt injection',p:'/prɑːmpt ɪnˈdʒekʃən/',z:'n. 提示词注入',e:'Prompt injection is a security risk.'},
  {w:'quantization',p:'/ˌkwɑːntəˈzeɪʃən/',z:'n. 量化',e:'Quantization can make a model smaller.'},
  {w:'recommendation',p:'/ˌrekəmenˈdeɪʃən/',z:'n. 推荐',e:'The recommendation matches my interests.'},
  {w:'reinforcement learning',p:'/ˌriːɪnˈfɔːrsmənt ˈlɜːrnɪŋ/',z:'n. 强化学习',e:'Reinforcement learning uses rewards.'},
  {w:'retrieval',p:'/rɪˈtriːvəl/',z:'n. 检索',e:'Retrieval brings useful documents into context.'},
  {w:'robotics',p:'/roʊˈbɑːtɪks/',z:'n. 机器人学',e:'Robotics combines software and hardware.'},
  {w:'safety',p:'/ˈseɪfti/',z:'n. 安全',e:'Safety comes before speed.'},
  {w:'semantic',p:'/sɪˈmæntɪk/',z:'adj. 语义的',e:'Semantic search looks at meaning.'},
  {w:'speech recognition',p:'/spiːtʃ ˌrekəɡˈnɪʃən/',z:'n. 语音识别',e:'Speech recognition works better in a quiet room.'},
  {w:'speech-to-text',p:'/spiːtʃ tə tekst/',z:'n. 语音转文字',e:'Speech-to-text saves typing time.'},
  {w:'synthetic data',p:'/sɪnˈθetɪk ˈdeɪtə/',z:'n. 合成数据',e:'Synthetic data can support testing.'},
  {w:'system prompt',p:'/ˈsɪstəm prɑːmpt/',z:'n. 系统提示词',e:'The system prompt sets the task rules.'},
  {w:'temperature',p:'/ˈtemprətʃər/',z:'n. 温度参数',e:'A lower temperature gives steadier output.'},
  {w:'text-to-speech',p:'/tekst tə spiːtʃ/',z:'n. 文字转语音',e:'Text-to-speech reads the sentence aloud.'},
  {w:'training data',p:'/ˈtreɪnɪŋ ˈdeɪtə/',z:'n. 训练数据',e:'Good training data improves results.'},
  {w:'vector',p:'/ˈvektər/',z:'n. 向量',e:'A vector represents a point in a space.'},
  {w:'vector database',p:'/ˈvektər ˈdeɪtəbeɪs/',z:'n. 向量数据库',e:'The vector database stores embeddings.'},
  {w:'watermark',p:'/ˈwɔːtərmɑːrk/',z:'n. 水印',e:'The image includes a visible watermark.'},
  {w:'workflow',p:'/ˈwɜːrkfloʊ/',z:'n. 工作流程',e:'The workflow has three simple steps.'},
  {w:'zero-shot',p:'/ˈzɪroʊ ʃɑːt/',z:'adj. 零样本的',e:'Zero-shot classification needs no examples.'},
  {w:'few-shot',p:'/fjuː ʃɑːt/',z:'adj. 少样本的',e:'Few-shot learning uses a few examples.'},
  {w:'chain of thought',p:'/tʃeɪn əv θɔːt/',z:'n. 思维链',e:'The lesson explains the idea step by step.'},
  {w:'computer program',p:'/kəmˈpjuːtər ˈproʊɡræm/',z:'n. 计算机程序',e:'A computer program follows instructions.'},
  {w:'code editor',p:'/koʊd ˈedɪtər/',z:'n. 代码编辑器',e:'Open the file in a code editor.'},
  {w:'command line',p:'/kəˈmænd laɪn/',z:'n. 命令行',e:'The command line gives direct control.'},
  {w:'console',p:'/kənˈsoʊl/',z:'n. 控制台',e:'The error appears in the console.'},
  {w:'terminal',p:'/ˈtɜːrmɪnəl/',z:'n. 终端',e:'Run the script in the terminal.'},
  {w:'data format',p:'/ˈdeɪtə ˈfɔːrmæt/',z:'n. 数据格式',e:'JSON is a common data format.'},
  {w:'data point',p:'/ˈdeɪtə pɔɪnt/',z:'n. 数据点',e:'Each data point has a label.'},
  {w:'data cleaning',p:'/ˈdeɪtə ˈkliːnɪŋ/',z:'n. 数据清洗',e:'Data cleaning removes repeated rows.'},
  {w:'data flow',p:'/ˈdeɪtə floʊ/',z:'n. 数据流',e:'The diagram shows the data flow.'},
  {w:'feature engineering',p:'/ˈfiːtʃər ˌendʒəˈnɪrɪŋ/',z:'n. 特征工程',e:'Feature engineering can improve a model.'},
  {w:'model card',p:'/ˈmɑːdl kɑːrd/',z:'n. 模型卡片',e:'Read the model card before use.'},
  {w:'model size',p:'/ˈmɑːdl saɪz/',z:'n. 模型大小',e:'Model size affects memory use.'},
  {w:'model output',p:'/ˈmɑːdl ˈaʊtpʊt/',z:'n. 模型输出',e:'Check the model output carefully.'},
  {w:'accuracy',p:'/ˈækjərəsi/',z:'n. 准确率',e:'Accuracy is only one way to measure quality.'},
  {w:'bias',p:'/ˈbaɪəs/',z:'n. 偏差；偏见',e:'The test looks for bias in the data.'},
  {w:'consent',p:'/kənˈsent/',z:'n. 同意',e:'Ask for consent before collecting a photo.'},
  {w:'copyright',p:'/ˈkɑːpiraɪt/',z:'n. 版权',e:'Respect copyright when sharing content.'},
  {w:'dataset card',p:'/ˈdeɪtəset kɑːrd/',z:'n. 数据集说明卡',e:'The dataset card describes the source.'},
  {w:'disclosure',p:'/dɪˈskloʊʒər/',z:'n. 披露',e:'The report includes an AI disclosure.'},
  {w:'explainability',p:'/ɪkˌspleɪnəˈbɪləti/',z:'n. 可解释性',e:'Explainability matters in education.'},
  {w:'fairness',p:'/ˈfernəs/',z:'n. 公平性',e:'Fairness should be tested with care.'},
  {w:'human review',p:'/ˈhjuːmən rɪˈvjuː/',z:'n. 人工复核',e:'Important answers need human review.'},
  {w:'model card',p:'/ˈmɑːdl kɑːrd/',z:'n. 模型卡片',e:'The model card lists known limits.'},
  {w:'open model',p:'/ˈoʊpən ˈmɑːdl/',z:'n. 开放模型',e:'The open model has a public license.'},
  {w:'red team',p:'/red tiːm/',z:'n. 红队测试团队',e:'The red team searches for weaknesses.'},
  {w:'responsible AI',p:'/rɪˈspɑːnsəbəl eɪ aɪ/',z:'n. 负责任的人工智能',e:'Responsible AI protects users.'},
  {w:'risk assessment',p:'/rɪsk əˈsesmənt/',z:'n. 风险评估',e:'Complete a risk assessment first.'},
  {w:'safety filter',p:'/ˈseɪfti ˈfɪltər/',z:'n. 安全过滤器',e:'The safety filter blocks harmful requests.'},
  {w:'training run',p:'/ˈtreɪnɪŋ rʌn/',z:'n. 训练轮次',e:'The training run finished overnight.'},
  {w:'usage policy',p:'/ˈjuːsɪdʒ ˈpɑːləsi/',z:'n. 使用规范',e:'Read the usage policy before sharing.'},
  {w:'version control',p:'/ˈvɜːrʒən kənˈtroʊl/',z:'n. 版本控制',e:'Version control keeps a history of changes.'},
  {w:'webhook',p:'/ˈwebhʊk/',z:'n. 网络钩子',e:'The webhook sends an event to another service.'},
  {w:'web app',p:'/web æp/',z:'n. 网页应用',e:'The web app works on a phone.'},
  {w:'user experience',p:'/ˈjuːzər ɪkˈspɪriəns/',z:'n. 用户体验',e:'A clear layout improves user experience.'},
  {w:'user interface',p:'/ˈjuːzər ˈɪntərfeɪs/',z:'n. 用户界面',e:'The user interface is easy to understand.'},
  {w:'voice assistant',p:'/vɔɪs əˈsɪstənt/',z:'n. 语音助手',e:'A voice assistant can set a timer.'},
  {w:'virtual reality',p:'/ˈvɜːrtʃuəl riˈæləti/',z:'n. 虚拟现实',e:'Virtual reality creates an immersive scene.'},
  {w:'augmented reality',p:'/ɔːɡˈmentɪd riˈæləti/',z:'n. 增强现实',e:'Augmented reality adds information to a view.'},
  {w:'digital twin',p:'/ˈdɪdʒɪtəl twɪn/',z:'n. 数字孪生',e:'A digital twin models a real machine.'},
  {w:'edge computing',p:'/edʒ kəmˈpjuːtɪŋ/',z:'n. 边缘计算',e:'Edge computing reduces network delay.'},
  {w:'cloud computing',p:'/klaʊd kəmˈpjuːtɪŋ/',z:'n. 云计算',e:'Cloud computing provides flexible resources.'},
  {w:'open standard',p:'/ˈoʊpən ˈstændərd/',z:'n. 开放标准',e:'An open standard helps systems work together.'},
  {w:'software agent',p:'/ˈsɔːftwer ˈeɪdʒənt/',z:'n. 软件智能体',e:'A software agent can watch a workflow.'},
  {w:'task planning',p:'/tæsk ˈplænɪŋ/',z:'n. 任务规划',e:'Task planning breaks a goal into steps.'},
  {w:'tool use',p:'/tuːl juːs/',z:'n. 工具使用',e:'Tool use lets the assistant take an action.'},
  {w:'memory retrieval',p:'/ˈmeməri rɪˈtriːvəl/',z:'n. 记忆检索',e:'Memory retrieval brings back useful notes.'},
  {w:'long context',p:'/lɔːŋ ˈkɑːntekst/',z:'n. 长上下文',e:'Long context helps with a large document.'},
  {w:'short answer',p:'/ʃɔːrt ˈænsər/',z:'n. 简短回答',e:'Ask for a short answer when you are in a hurry.'},
  {w:'structured output',p:'/ˈstrʌktʃərd ˈaʊtpʊt/',z:'n. 结构化输出',e:'Structured output is easier to check.'},
  {w:'batch processing',p:'/bætʃ ˈprɑːsesɪŋ/',z:'n. 批处理',e:'Batch processing handles many files together.'},
  {w:'real time',p:'/riːl taɪm/',z:'adj. 实时的',e:'The dashboard shows real time results.'},
  {w:'latency budget',p:'/ˈleɪtənsi ˈbʌdʒɪt/',z:'n. 延迟预算',e:'The team set a latency budget.'},
  {w:'load test',p:'/loʊd test/',z:'n. 负载测试',e:'Run a load test before launch.'},
  {w:'monitoring',p:'/ˈmɑːnɪtərɪŋ/',z:'n. 监控',e:'Monitoring helps find failures early.'},
  {w:'observability',p:'/əbˌzɜːrvəˈbɪləti/',z:'n. 可观测性',e:'Observability shows what happens inside a service.'},
  {w:'rollback',p:'/ˈroʊlbæk/',z:'v./n. 回滚',e:'Rollback the release if users see errors.'},
  {w:'scaling',p:'/ˈskeɪlɪŋ/',z:'n. 扩展规模',e:'Scaling keeps the app responsive.'},
  {w:'uptime',p:'/ˈʌptaɪm/',z:'n. 正常运行时间',e:'The service has high uptime.'},
  {w:'access token',p:'/ˈækses ˈtoʊkən/',z:'n. 访问令牌',e:'Never share an access token.'},
  {w:'secret key',p:'/ˈsiːkrət kiː/',z:'n. 密钥',e:'Keep the secret key private.'},
  {w:'secure storage',p:'/sɪˈkjʊr ˈstɔːrɪdʒ/',z:'n. 安全存储',e:'Use secure storage for private data.'},
  {w:'two-factor authentication',p:'/tuː ˈfæktər ɔːˌθentɪˈkeɪʃən/',z:'n. 双因素认证',e:'Two-factor authentication protects the account.'},
  {w:'vulnerability',p:'/ˌvʌlnərəˈbɪləti/',z:'n. 漏洞',e:'The patch fixes a security vulnerability.'},
  {w:'zero trust',p:'/ˈzɪroʊ trʌst/',z:'n. 零信任',e:'Zero trust checks every request.'},
  {w:'content filter',p:'/ˈkɑːntent ˈfɪltər/',z:'n. 内容过滤器',e:'The content filter hides unsafe material.'},
  {w:'content moderation',p:'/ˈkɑːntent ˌmɑːdəˈreɪʃən/',z:'n. 内容审核',e:'Content moderation needs clear rules.'},
  {w:'fact check',p:'/fækt tʃek/',z:'v./n. 事实核查',e:'Fact check an important claim.'},
  {w:'source citation',p:'/sɔːrs saɪˈteɪʃən/',z:'n. 来源引用',e:'Add a source citation to the report.'},
  {w:'knowledge graph',p:'/ˈnɑːlɪdʒ ɡræf/',z:'n. 知识图谱',e:'A knowledge graph connects related facts.'},
  {w:'entity',p:'/ˈentəti/',z:'n. 实体',e:'The system finds each entity in the text.'},
  {w:'relation',p:'/rɪˈleɪʃən/',z:'n. 关系',e:'The graph stores a relation between two entities.'},
  {w:'tokenizer',p:'/ˈtoʊkənaɪzər/',z:'n. 分词器',e:'A tokenizer splits text into tokens.'},
  {w:'vocabulary',p:'/vəˈkæbjəleri/',z:'n. 词汇表',e:'The model has a large vocabulary.'},
  {w:'context window',p:'/ˈkɑːntekst ˈwɪndoʊ/',z:'n. 上下文窗口',e:'A larger context window holds more text.'},
  {w:'language model',p:'/ˈlæŋɡwɪdʒ ˈmɑːdl/',z:'n. 语言模型',e:'A language model predicts the next token.'},
  {w:'base model',p:'/beɪs ˈmɑːdl/',z:'n. 基础模型',e:'The base model can be adapted for a task.'},
  {w:'instruction tuning',p:'/ɪnˈstrʌkʃən ˈtuːnɪŋ/',z:'n. 指令微调',e:'Instruction tuning improves task following.'},
  {w:'alignment',p:'/əˈlaɪnmənt/',z:'n. 对齐',e:'Alignment helps the model follow user goals.'},
  {w:'benchmark test',p:'/ˈbentʃmɑːrk test/',z:'n. 基准测试',e:'The benchmark test compares two models.'},
  {w:'leaderboard',p:'/ˈliːdərbɔːrd/',z:'n. 排行榜',e:'The leaderboard shows test results.'},
  {w:'hallucination rate',p:'/həˌluːsəˈneɪʃən reɪt/',z:'n. 幻觉率',e:'The team tracks the hallucination rate.'},
  {w:'human feedback',p:'/ˈhjuːmən ˈfiːdbæk/',z:'n. 人类反馈',e:'Human feedback improves the assistant.'},
  {w:'preference',p:'/ˈprefərəns/',z:'n. 偏好',e:'The app remembers your language preference.'},
  {w:'personalization',p:'/ˌpɜːrsənələˈzeɪʃən/',z:'n. 个性化',e:'Personalization makes practice more useful.'},
  {w:'translation',p:'/trænzˈleɪʃən/',z:'n. 翻译',e:'The translation keeps the original meaning.'},
  {w:'summarization',p:'/ˌsʌməraɪˈzeɪʃən/',z:'n. 摘要生成',e:'Summarization turns a long article into notes.'},
  {w:'classification model',p:'/ˌklæsɪfɪˈkeɪʃən ˈmɑːdl/',z:'n. 分类模型',e:'The classification model sorts the emails.'},
  {w:'search index',p:'/sɜːrtʃ ˈɪndeks/',z:'n. 搜索索引',e:'The search index is updated every hour.'},
  {w:'ranker',p:'/ˈræŋkər/',z:'n. 排序模型',e:'The ranker puts useful results first.'},
  {w:'relevance',p:'/ˈreləvəns/',z:'n. 相关性',e:'The result has high relevance to the question.'},
  {w:'recall',p:'/rɪˈkɔːl/',z:'n. 召回率；回忆',e:'The search has good recall.'},
  {w:'precision',p:'/prɪˈsɪʒən/',z:'n. 精确率',e:'Precision measures the useful results.'},
  {w:'test case',p:'/test keɪs/',z:'n. 测试用例',e:'Add a test case for this behavior.'},
  {w:'unit test',p:'/ˈjuːnɪt test/',z:'n. 单元测试',e:'A unit test checks one small function.'},
  {w:'integration test',p:'/ˌɪntɪˈɡreɪʃən test/',z:'n. 集成测试',e:'The integration test checks the full flow.'},
  {w:'continuous integration',p:'/kənˈtɪnjuəs ˌɪntɪˈɡreɪʃən/',z:'n. 持续集成',e:'Continuous integration catches errors early.'},
  {w:'build pipeline',p:'/bɪld ˈpaɪplaɪn/',z:'n. 构建流程',e:'The build pipeline runs after each commit.'},
  {w:'source code',p:'/sɔːrs koʊd/',z:'n. 源代码',e:'Keep the source code readable.'},
  {w:'bug report',p:'/bʌɡ rɪˈpɔːrt/',z:'n. 缺陷报告',e:'Write a clear bug report.'},
  {w:'issue tracker',p:'/ˈɪʃuː ˈtrækər/',z:'n. 问题跟踪器',e:'The issue tracker lists open work.'},
  {w:'pull request review',p:'/pʊl rɪˈkwest rɪˈvjuː/',z:'n. 拉取请求审查',e:'The pull request review found a typo.'},
  {w:'release note',p:'/rɪˈliːs noʊt/',z:'n. 发布说明',e:'Read the release note for changes.'},
  {w:'feature flag',p:'/ˈfiːtʃər flæɡ/',z:'n. 功能开关',e:'Use a feature flag for a gradual launch.'},
  {w:'rollout',p:'/ˈroʊlaʊt/',z:'n. 发布推广',e:'The rollout starts with a small group.'},
  {w:'incident',p:'/ˈɪnsɪdənt/',z:'n. 故障事件',e:'The team wrote an incident report.'},
  {w:'postmortem',p:'/poʊstˈmɔːrtəm/',z:'n. 事后复盘',e:'The postmortem explains what happened.'},
  {w:'service level',p:'/ˈsɜːrvɪs ˈlevəl/',z:'n. 服务等级',e:'The service level sets a clear target.'},
  {w:'availability',p:'/əˌveɪləˈbɪləti/',z:'n. 可用性',e:'Availability is important for a daily app.'},
  {w:'backup plan',p:'/ˈbækʌp plæn/',z:'n. 备用方案',e:'Keep a backup plan for the launch.'},
  {w:'access control',p:'/ˈækses kənˈtroʊl/',z:'n. 访问控制',e:'Access control limits who can view data.'},
  {w:'permission',p:'/pərˈmɪʃən/',z:'n. 权限',e:'The app asks for permission to use the microphone.'},
  {w:'role',p:'/roʊl/',z:'n. 角色',e:'Each role has different permissions.'},
  {w:'audit log',p:'/ˈɔːdɪt lɔːɡ/',z:'n. 审计日志',e:'The audit log records important actions.'},
  {w:'encryption key',p:'/ɪnˈkrɪpʃən kiː/',z:'n. 加密密钥',e:'Protect the encryption key.'},
  {w:'secure connection',p:'/sɪˈkjʊr kəˈnekʃən/',z:'n. 安全连接',e:'Use a secure connection on public Wi-Fi.'},
  {w:'malware',p:'/ˈmælwer/',z:'n. 恶意软件',e:'The scanner found malware.'},
  {w:'phishing',p:'/ˈfɪʃɪŋ/',z:'n. 网络钓鱼',e:'Phishing messages often create urgency.'},
  {w:'spam',p:'/spæm/',z:'n. 垃圾信息',e:'The filter moves spam to a separate folder.'},
  {w:'rate control',p:'/reɪt kənˈtroʊl/',z:'n. 速率控制',e:'Rate control protects the service.'},
  {w:'quota',p:'/ˈkwoʊtə/',z:'n. 配额',e:'The account has a daily quota.'},
  {w:'cost estimate',p:'/kɔːst ˈestəmət/',z:'n. 成本估算',e:'The cost estimate includes storage.'},
  {w:'usage report',p:'/ˈjuːsɪdʒ rɪˈpɔːrt/',z:'n. 使用报告',e:'The usage report shows this month.'},
  {w:'subscription plan',p:'/səbˈskrɪpʃən plæn/',z:'n. 订阅方案',e:'Choose a subscription plan that fits.'},
  {w:'free tier',p:'/friː tɪr/',z:'n. 免费层级',e:'The free tier is enough for testing.'},
  {w:'usage limit',p:'/ˈjuːsɪdʒ ˈlɪmɪt/',z:'n. 使用上限',e:'The usage limit resets each day.'},
  {w:'pricing',p:'/ˈpraɪsɪŋ/',z:'n. 定价',e:'Check the pricing before launch.'},
  {w:'license',p:'/ˈlaɪsəns/',z:'n. 许可证',e:'Read the license before reuse.'},
  {w:'open source license',p:'/ˈoʊpən sɔːrs ˈlaɪsəns/',z:'n. 开源许可证',e:'The open source license allows reuse.'},
  {w:'community',p:'/kəˈmjuːnəti/',z:'n. 社区',e:'The community shares helpful tools.'},
  {w:'maintainer',p:'/meɪnˈteɪnər/',z:'n. 维护者',e:'The maintainer reviews new changes.'},
  {w:'contributor',p:'/kənˈtrɪbjətər/',z:'n. 贡献者',e:'Every contributor follows the guide.'},
  {w:'documentation',p:'/ˌdɑːkjəmenˈteɪʃən/',z:'n. 文档资料',e:'Good documentation helps beginners.'},
  {w:'quickstart',p:'/ˈkwɪkstɑːrt/',z:'n. 快速入门',e:'The quickstart takes five minutes.'},
  {w:'tutorial',p:'/tuːˈtɔːriəl/',z:'n. 教程',e:'Follow the tutorial step by step.'},
  {w:'sample',p:'/ˈsæmpəl/',z:'n. 示例',e:'Start with the sample project.'},
  {w:'template',p:'/ˈtemplət/',z:'n. 模板',e:'Use the template to begin.'},
  {w:'migration',p:'/maɪˈɡreɪʃən/',z:'n. 迁移',e:'The migration moved old data safely.'},
  {w:'compatibility',p:'/kəmˌpætəˈbɪləti/',z:'n. 兼容性',e:'Test compatibility on two browsers.'},
  {w:'dependency conflict',p:'/dɪˈpendənsi ˈkɑːnflɪkt/',z:'n. 依赖冲突',e:'The dependency conflict stopped the build.'},
  {w:'environment variable',p:'/ɪnˈvaɪrənmənt ˈveriəbəl/',z:'n. 环境变量',e:'Store the setting in an environment variable.'},
  {w:'local development',p:'/ˈloʊkəl dɪˈveləpmənt/',z:'n. 本地开发',e:'Local development is useful for testing.'},
  {w:'production',p:'/prəˈdʌkʃən/',z:'n. 生产环境',e:'Check the change before production.'},
  {w:'staging',p:'/ˈsteɪdʒɪŋ/',z:'n. 预发布环境',e:'The update is ready for staging.'},
  {w:'preview',p:'/ˈpriːvjuː/',z:'n./v. 预览',e:'Open the preview before sharing.'},
  {w:'responsive design',p:'/rɪˈspɑːnsɪv dɪˈzaɪn/',z:'n. 响应式设计',e:'Responsive design works on small screens.'},
  {w:'mobile first',p:'/ˈmoʊbəl fɜːrst/',z:'adj. 移动端优先的',e:'The mobile first layout is easy to use.'},
  {w:'dark mode',p:'/dɑːrk moʊd/',z:'n. 深色模式',e:'Dark mode is comfortable at night.'},
  {w:'notification setting',p:'/ˌnoʊtɪfɪˈkeɪʃən ˈsetɪŋ/',z:'n. 通知设置',e:'Change the notification setting anytime.'},
  {w:'offline mode',p:'/ˌɔːfˈlaɪn moʊd/',z:'n. 离线模式',e:'Offline mode keeps basic practice available.'},
  {w:'sync status',p:'/sɪŋk ˈsteɪtəs/',z:'n. 同步状态',e:'Check the sync status before leaving.'},
  {w:'cross-device',p:'/krɔːs dɪˈvaɪs/',z:'adj. 跨设备的',e:'Cross-device progress needs a shared account.'},
  {w:'study mode',p:'/ˈstʌdi moʊd/',z:'n. 学习模式',e:'Study mode shows one word at a time.'},
  {w:'practice session',p:'/ˈpræktɪs ˈseʃən/',z:'n. 练习时段',e:'Start a short practice session today.'},
  {w:'learning progress',p:'/ˈlɜːrnɪŋ ˈprɑːɡres/',z:'n. 学习进度',e:'The app saves learning progress.'},
  {w:'spaced repetition',p:'/speɪst ˌrepəˈtɪʃən/',z:'n. 间隔重复',e:'Spaced repetition brings back difficult words.'},
  {w:'review queue',p:'/rɪˈvjuː kjuː/',z:'n. 复习队列',e:'The review queue shows words to revisit.'},
  {w:'mastery',p:'/ˈmæstəri/',z:'n. 掌握',e:'Mastery takes regular practice.'},
  {w:'pronunciation',p:'/prəˌnʌnsiˈeɪʃən/',z:'n. 发音',e:'Listen to the pronunciation twice.'},
  {w:'speech rate',p:'/spiːtʃ reɪt/',z:'n. 语速',e:'Lower the speech rate for beginners.'},
  {w:'read aloud',p:'/riːd əˈlaʊd/',z:'v. 大声朗读',e:'Read aloud and repeat the sentence.'},
  {w:'voice playback',p:'/vɔɪs ˈpleɪbæk/',z:'n. 语音播放',e:'Tap the card for voice playback.'},
  {w:'word bank',p:'/wɜːrd bæŋk/',z:'n. 词库',e:'Choose a word bank for today.'},
  {w:'daily goal',p:'/ˈdeɪli ɡoʊl/',z:'n. 每日目标',e:'Set a small daily goal.'},
  {w:'streak',p:'/striːk/',z:'n. 连续记录',e:'Keep your learning streak alive.'},
  {w:'progress bar',p:'/ˈprɑːɡres bɑːr/',z:'n. 进度条',e:'The progress bar moves as you learn.'},
  {w:'account switch',p:'/əˈkaʊnt swɪtʃ/',z:'n. 账号切换',e:'Use account switch on a shared phone.'},
  {w:'sign in',p:'/saɪn ɪn/',z:'v. 登录',e:'Sign in to continue your practice.'},
  {w:'sign out',p:'/saɪn aʊt/',z:'v. 退出登录',e:'Sign out on a public computer.'},
  {w:'remember me',p:'/rɪˈmembər miː/',z:'v. 记住登录状态',e:'Choose remember me on your own phone.'},
  {w:'data isolation',p:'/ˈdeɪtə ˌaɪsəˈleɪʃən/',z:'n. 数据隔离',e:'Data isolation keeps two profiles separate.'},
  {w:'family account',p:'/ˈfæməli əˈkaʊnt/',z:'n. 家庭账号',e:'A family account can hold separate profiles.'},
  {w:'private profile',p:'/ˈpraɪvət ˈproʊfaɪl/',z:'n. 私人资料',e:'Each learner has a private profile.'},
  {w:'backup copy',p:'/ˈbækʌp ˈkɑːpi/',z:'n. 备份副本',e:'Keep a backup copy of important notes.'},
  {w:'export file',p:'/ˈekspɔːrt faɪl/',z:'n. 导出文件',e:'Save an export file before moving devices.'},
  {w:'import file',p:'/ˈɪmpɔːrt faɪl/',z:'n. 导入文件',e:'Import file lets you restore a list.'},
  {w:'data format',p:'/ˈdeɪtə ˈfɔːrmæt/',z:'n. 数据格式',e:'Choose a simple data format for backup.'},
  {w:'local storage',p:'/ˈloʊkəl ˈstɔːrɪdʒ/',z:'n. 本地存储',e:'Local storage keeps data in this browser.'},
  {w:'cloud backup',p:'/klaʊd ˈbækʌp/',z:'n. 云备份',e:'Cloud backup helps across devices.'},
  {w:'restore point',p:'/rɪˈstɔːr pɔɪnt/',z:'n. 恢复点',e:'Create a restore point before a change.'},
  {w:'data export',p:'/ˈdeɪtə ˈekspɔːrt/',z:'n. 数据导出',e:'Data export gives you a copy of your progress.'},
  {w:'data import',p:'/ˈdeɪtə ˈɪmpɔːrt/',z:'n. 数据导入',e:'Data import brings back your word list.'},
  {w:'file format',p:'/faɪl ˈfɔːrmæt/',z:'n. 文件格式',e:'Check the file format before importing.'},
  {w:'preview link',p:'/ˈpriːvjuː lɪŋk/',z:'n. 预览链接',e:'Send the preview link to a tester.'},
  {w:'share link',p:'/ʃer lɪŋk/',z:'n. 分享链接',e:'Copy the share link after saving.'},
  {w:'accessibility mode',p:'/əkˌsesəˈbɪləti moʊd/',z:'n. 无障碍模式',e:'Accessibility mode makes text easier to read.'},
  {w:'screen reader',p:'/skriːn ˈriːdər/',z:'n. 屏幕阅读器',e:'A screen reader reads the labels aloud.'},
  {w:'keyboard shortcut',p:'/ˈkiːbɔːrd ˈʃɔːrtkʌt/',z:'n. 键盘快捷键',e:'Use a keyboard shortcut to save time.'},
  {w:'touch target',p:'/tʌtʃ ˈtɑːrɡɪt/',z:'n. 触控区域',e:'A large touch target is easier on a phone.'},
  {w:'loading state',p:'/ˈloʊdɪŋ steɪt/',z:'n. 加载状态',e:'The loading state tells users to wait.'},
  {w:'empty state',p:'/ˈempti steɪt/',z:'n. 空状态',e:'The empty state suggests the next action.'},
  {w:'error message',p:'/ˈerər ˈmesɪdʒ/',z:'n. 错误提示',e:'A clear error message helps users recover.'},
  {w:'success message',p:'/səkˈses ˈmesɪdʒ/',z:'n. 成功提示',e:'The success message confirms the save.'},
  {w:'retry',p:'/riˈtraɪ/',z:'v. 重试',e:'Tap retry when the connection returns.'},
  {w:'fallback',p:'/ˈfɔːlbæk/',z:'n. 备用方案',e:'The fallback keeps the page useful offline.'},
  {w:'graceful degradation',p:'/ˈɡreɪsfəl ˌdeɡrəˈdeɪʃən/',z:'n. 平稳降级',e:'Graceful degradation keeps basic features working.'},
  {w:'health check',p:'/helθ tʃek/',z:'n. 健康检查',e:'The health check runs every minute.'},
  {w:'status page',p:'/ˈsteɪtəs peɪdʒ/',z:'n. 状态页面',e:'The status page shows current incidents.'},
  {w:'service desk',p:'/ˈsɜːrvɪs desk/',z:'n. 服务台',e:'Contact the service desk for help.'},
  {w:'support ticket',p:'/səˈpɔːrt ˈtɪkɪt/',z:'n. 支持工单',e:'Create a support ticket with details.'},
  {w:'release channel',p:'/rɪˈliːs ˈtʃænəl/',z:'n. 发布渠道',e:'Choose the stable release channel.'},
  {w:'stable version',p:'/ˈsteɪbəl ˈvɜːrʒən/',z:'n. 稳定版本',e:'Use the stable version for daily work.'},
  {w:'beta version',p:'/ˈbeɪtə ˈvɜːrʒən/',z:'n. 测试版本',e:'The beta version may change quickly.'},
  {w:'early access',p:'/ˈɜːrli ˈækses/',z:'n. 提前体验',e:'Early access is open to a small group.'},
  {w:'feedback form',p:'/ˈfiːdbæk fɔːrm/',z:'n. 反馈表单',e:'Fill out the feedback form after practice.'},
  {w:'user research',p:'/ˈjuːzər rɪˈsɜːrtʃ/',z:'n. 用户研究',e:'User research reveals what learners need.'},
  {w:'product idea',p:'/ˈprɑːdʌkt aɪˈdiːə/',z:'n. 产品想法',e:'Write down the product idea.'},
  {w:'design brief',p:'/dɪˈzaɪn briːf/',z:'n. 设计简报',e:'The design brief explains the goal.'},
  {w:'success criteria',p:'/səkˈses kraɪˈtɪriə/',z:'n. 成功标准',e:'Agree on success criteria before building.'},
  {w:'user story',p:'/ˈjuːzər ˈstɔːri/',z:'n. 用户故事',e:'The user story describes a real need.'},
  {w:'acceptance test',p:'/əkˈseptəns test/',z:'n. 验收测试',e:'The acceptance test checks the finished flow.'},
  {w:'prototype',p:'/ˈproʊtətaɪp/',z:'n. 原型',e:'The prototype makes the idea visible.'},
  {w:'iteration cycle',p:'/ˌɪtəˈreɪʃən ˈsaɪkəl/',z:'n. 迭代周期',e:'Each iteration cycle ends with a review.'},
  {w:'priority',p:'/praɪˈɔːrəti/',z:'n. 优先级',e:'Learning quality is the first priority.'},
  {w:'scope',p:'/skoʊp/',z:'n. 范围',e:'Keep the first release within scope.'},
  {w:'trade-off',p:'/ˈtreɪd ɔːf/',z:'n. 权衡',e:'Every design has a trade-off.'},
  {w:'constraint',p:'/kənˈstreɪnt/',z:'n. 约束',e:'Time is an important constraint.'},
  {w:'milestone',p:'/ˈmaɪlstoʊn/',z:'n. 里程碑',e:'The first working page is a milestone.'},
  {w:'checklist',p:'/ˈtʃeklɪst/',z:'n. 检查清单',e:'Use a checklist before publishing.'},
  {w:'handoff',p:'/ˈhændɔːf/',z:'n. 交接',e:'The handoff includes notes and tests.'},
  {w:'maintenance',p:'/ˈmeɪntənəns/',z:'n. 维护',e:'Regular maintenance keeps the app healthy.'},
  {w:'upgrade path',p:'/ʌpˈɡreɪd pæθ/',z:'n. 升级路径',e:'The upgrade path is documented.'},
  {w:'backward compatibility',p:'/ˈbækwərd kəmˌpætəˈbɪləti/',z:'n. 向后兼容',e:'Backward compatibility protects old data.'},
  {w:'data migration',p:'/ˈdeɪtə maɪˈɡreɪʃən/',z:'n. 数据迁移',e:'The data migration completed safely.'},
  {w:'schema',p:'/ˈskiːmə/',z:'n. 数据结构',e:'The schema describes each field.'},
  {w:'field',p:'/fiːld/',z:'n. 字段',e:'The form has a required field.'},
  {w:'record',p:'/ˈrekərd/',z:'n. 记录',e:'Each record stores one learner.'},
  {w:'query language',p:'/ˈkwɪri ˈlæŋɡwɪdʒ/',z:'n. 查询语言',e:'A query language finds matching records.'},
  {w:'data model',p:'/ˈdeɪtə ˈmɑːdl/',z:'n. 数据模型',e:'The data model keeps progress separate.'},
  {w:'validation rule',p:'/ˌvæləˈdeɪʃən ruːl/',z:'n. 校验规则',e:'The validation rule checks the password.'},
  {w:'input field',p:'/ˈɪnpʊt fiːld/',z:'n. 输入框',e:'Tap the input field to type.'},
  {w:'form submission',p:'/fɔːrm səbˈmɪʃən/',z:'n. 表单提交',e:'The form submission was successful.'},
  {w:'request body',p:'/rɪˈkwest ˈbɑːdi/',z:'n. 请求体',e:'The request body contains the new data.'},
  {w:'response body',p:'/rɪˈspɑːns ˈbɑːdi/',z:'n. 响应体',e:'The response body contains the result.'},
  {w:'network error',p:'/ˈnetwɜːrk ˈerər/',z:'n. 网络错误',e:'A network error stopped the request.'},
  {w:'connection',p:'/kəˈnekʃən/',z:'n. 连接',e:'The connection is stable now.'},
  {w:'reconnect',p:'/ˌriːkəˈnekt/',z:'v. 重新连接',e:'Tap reconnect after the network returns.'},
  {w:'offline',p:'/ˌɔːfˈlaɪn/',z:'adj. 离线的',e:'The app works offline for basic practice.'},
  {w:'online',p:'/ˌɑːnˈlaɪn/',z:'adj. 在线的',e:'The online version saves changes.'},
  {w:'device',p:'/dɪˈvaɪs/',z:'n. 设备',e:'Open the app on another device.'},
  {w:'phone browser',p:'/foʊn ˈbraʊzər/',z:'n. 手机浏览器',e:'The phone browser supports the page.'},
  {w:'home screen',p:'/hoʊm skriːn/',z:'n. 主屏幕',e:'Add the app to your home screen.'},
  {w:'shortcut',p:'/ˈʃɔːrtkʌt/',z:'n. 快捷方式',e:'The shortcut opens the word bank.'},
  {w:'web standard',p:'/web ˈstændərd/',z:'n. 网页标准',e:'The page follows a web standard.'},
  {w:'browser storage',p:'/ˈbraʊzər ˈstɔːrɪdʒ/',z:'n. 浏览器存储',e:'Browser storage keeps the local settings.'},
  {w:'cache clear',p:'/kæʃ klɪr/',z:'n. 清除缓存',e:'A cache clear can fix an old page.'},
  {w:'refresh',p:'/rɪˈfreʃ/',z:'v. 刷新',e:'Refresh the page after the update.'},
  {w:'bookmark',p:'/ˈbʊkmɑːrk/',z:'n./v. 书签；收藏',e:'Bookmark the word bank for tomorrow.'},
  {w:'installable',p:'/ɪnˈstɔːləbəl/',z:'adj. 可安装的',e:'The web app is installable on a phone.'},
  {w:'shortcut icon',p:'/ˈʃɔːrtkʌt ˈaɪkɑːn/',z:'n. 快捷图标',e:'The shortcut icon is easy to recognize.'},
  {w:'app icon',p:'/æp ˈaɪkɑːn/',z:'n. 应用图标',e:'The app icon appears on the home screen.'},
  {w:'screen size',p:'/skriːn saɪz/',z:'n. 屏幕尺寸',e:'The layout adapts to screen size.'},
  {w:'font size',p:'/fɑːnt saɪz/',z:'n. 字体大小',e:'Increase the font size if needed.'},
  {w:'color contrast',p:'/ˈkʌlər ˈkɑːntræst/',z:'n. 色彩对比度',e:'Good color contrast helps reading.'},
  {w:'focus state',p:'/ˈfoʊkəs steɪt/',z:'n. 聚焦状态',e:'The focus state shows the active field.'},
  {w:'tap target',p:'/tæp ˈtɑːrɡɪt/',z:'n. 点击区域',e:'Make the tap target large enough.'},
  {w:'scroll position',p:'/skroʊl pəˈzɪʃən/',z:'n. 滚动位置',e:'The page remembers the scroll position.'},
  {w:'responsive layout',p:'/rɪˈspɑːnsɪv ˈleɪaʊt/',z:'n. 响应式布局',e:'A responsive layout fits the phone.'},
  {w:'progress record',p:'/ˈprɑːɡres ˈrekərd/',z:'n. 进度记录',e:'The progress record belongs to the learner.'},
  {w:'learning history',p:'/ˈlɜːrnɪŋ ˈhɪstəri/',z:'n. 学习历史',e:'Learning history shows earlier practice.'},
  {w:'daily review',p:'/ˈdeɪli rɪˈvjuː/',z:'n. 每日复习',e:'Daily review keeps words familiar.'},
  {w:'word card',p:'/wɜːrd kɑːrd/',z:'n. 单词卡片',e:'Tap a word card to hear it.'},
  {w:'example sentence',p:'/ɪɡˈzæmpəl ˈsentəns/',z:'n. 例句',e:'Read the example sentence aloud.'},
  {w:'meaning',p:'/ˈmiːnɪŋ/',z:'n. 含义',e:'Check the meaning before memorizing.'},
  {w:'phonetic symbol',p:'/fəˈnetɪk ˈsɪmbəl/',z:'n. 音标符号',e:'The phonetic symbol shows the sound.'},
  {w:'audio',p:'/ˈɔːdioʊ/',z:'n. 音频',e:'Tap the audio button.'},
  {w:'repeat',p:'/rɪˈpiːt/',z:'v. 重复',e:'Repeat the word three times.'},
  {w:'remember',p:'/rɪˈmembər/',z:'v. 记住',e:'Use an example to remember the word.'},
  {w:'forget',p:'/fərˈɡet/',z:'v. 忘记',e:'Review words before you forget them.'},
  {w:'difficulty',p:'/ˈdɪfɪkəlti/',z:'n. 难度',e:'The app can group words by difficulty.'},
  {w:'beginner',p:'/bɪˈɡɪnər/',z:'n. 初学者',e:'This list is friendly to a beginner.'},
  {w:'advanced',p:'/ədˈvænst/',z:'adj. 高级的',e:'The advanced list has longer terms.'},
  {w:'topic',p:'/ˈtɑːpɪk/',z:'n. 主题',e:'Choose a topic for today.'},
  {w:'category label',p:'/ˈkætəɡɔːri ˈleɪbəl/',z:'n. 分类标签',e:'The category label explains the list.'},
  {w:'word count',p:'/wɜːrd kaʊnt/',z:'n. 词数',e:'The word count appears in the menu.'},
  {w:'daily count',p:'/ˈdeɪli kaʊnt/',z:'n. 每日词数',e:'Set the daily count to five words.'},
  {w:'shuffle',p:'/ˈʃʌfəl/',z:'v. 打乱',e:'Shuffle the list for a new order.'},
  {w:'stable order',p:'/ˈsteɪbəl ˈɔːrdər/',z:'n. 稳定顺序',e:'A stable order helps you continue tomorrow.'},
  {w:'new batch',p:'/nuː bætʃ/',z:'n. 新的一批',e:'Tap the button for a new batch.'},
  {w:'learned',p:'/lɜːrnd/',z:'adj. 已学会的',e:'Learned words become lighter on the page.'},
  {w:'unlearned',p:'/ʌnˈlɜːrnd/',z:'adj. 未学会的',e:'Review the unlearned words first.'},
  {w:'statistics',p:'/stəˈtɪstɪks/',z:'n. 统计数据',e:'Open statistics to see your progress.'},
  {w:'study streak',p:'/ˈstʌdi striːk/',z:'n. 学习连续记录',e:'A study streak can build a habit.'},
  {w:'goal setting',p:'/ɡoʊl ˈsetɪŋ/',z:'n. 目标设定',e:'Goal setting makes practice clearer.'},
  {w:'habit',p:'/ˈhæbɪt/',z:'n. 习惯',e:'A small habit grows over time.'},
  {w:'consistency',p:'/kənˈsɪstənsi/',z:'n. 坚持；一致性',e:'Consistency matters more than speed.'},
  {w:'focus time',p:'/ˈfoʊkəs taɪm/',z:'n. 专注时间',e:'Protect ten minutes of focus time.'},
  {w:'break time',p:'/breɪk taɪm/',z:'n. 休息时间',e:'Take a short break time after practice.'},
  {w:'study plan',p:'/ˈstʌdi plæn/',z:'n. 学习计划',e:'A study plan keeps the week organized.'},
  {w:'learning goal',p:'/ˈlɜːrnɪŋ ɡoʊl/',z:'n. 学习目标',e:'Choose one learning goal for today.'},
  {w:'knowledge point',p:'/ˈnɑːlɪdʒ pɔɪnt/',z:'n. 知识点',e:'One knowledge point is enough for today.'},
  {w:'review note',p:'/rɪˈvjuː noʊt/',z:'n. 复习笔记',e:'Write a review note after practice.'},
  {w:'study material',p:'/ˈstʌdi məˈtɪriəl/',z:'n. 学习材料',e:'Keep study material in one place.'},
  {w:'lesson plan',p:'/ˈlesən plæn/',z:'n. 课程计划',e:'The lesson plan starts with a question.'},
  {w:'practice task',p:'/ˈpræktɪs tæsk/',z:'n. 练习任务',e:'Finish one practice task today.'},
  {w:'answer check',p:'/ˈænsər tʃek/',z:'n. 答案检查',e:'Use answer check after trying yourself.'},
  {w:'mistake review',p:'/mɪˈsteɪk rɪˈvjuː/',z:'n. 错题复习',e:'Mistake review helps you improve.'},
  {w:'transfer question',p:'/trænsˈfɜːr ˈkwestʃən/',z:'n. 迁移问题',e:'A transfer question checks real understanding.'},
  {w:'self check',p:'/self tʃek/',z:'n. 自我检查',e:'Do a self check before finishing.'},
  {w:'mastery check',p:'/ˈmæstəri tʃek/',z:'n. 掌握检查',e:'The mastery check asks you to explain.'},
  {w:'learning signal',p:'/ˈlɜːrnɪŋ ˈsɪɡnəl/',z:'n. 学习信号',e:'A correct answer is one learning signal.'},
  {w:'progress insight',p:'/ˈprɑːɡres ˈɪnsaɪt/',z:'n. 进度洞察',e:'Progress insight shows what to review.'},
  {w:'personal note',p:'/ˈpɜːrsənəl noʊt/',z:'n. 个人笔记',e:'Add a personal note to the word.'},
  {w:'quick entry',p:'/kwɪk ˈentri/',z:'n. 快速入口',e:'The home page has a quick entry to words.'},
  {w:'independent learning',p:'/ˌɪndɪˈpendənt ˈlɜːrnɪŋ/',z:'n. 自主学习',e:'The app supports independent learning.'},
  {w:'learning path',p:'/ˈlɜːrnɪŋ pæθ/',z:'n. 学习路径',e:'Choose a learning path that fits you.'},
  {w:'course map',p:'/kɔːrs mæp/',z:'n. 课程地图',e:'The course map shows the next step.'},
  {w:'subject menu',p:'/ˈsʌbdʒekt ˈmenjuː/',z:'n. 学科菜单',e:'Use the subject menu to switch topics.'},
  {w:'grade level',p:'/ɡreɪd ˈlevəl/',z:'n. 年级层级',e:'Choose the right grade level.'},
  {w:'textbook version',p:'/ˈtekstbʊk ˈvɜːrʒən/',z:'n. 教材版本',e:'Check the textbook version later.'},
  {w:'curriculum',p:'/kəˈrɪkjələm/',z:'n. 课程体系',e:'The word bank follows the curriculum.'},
  {w:'semester',p:'/səˈmestər/',z:'n. 学期',e:'This list is for the first semester.'},
  {w:'term one',p:'/tɜːrm wʌn/',z:'n. 上学期',e:'Start with term one vocabulary.'},
  {w:'unit',p:'/ˈjuːnɪt/',z:'n. 单元',e:'The word belongs to Unit One.'},
  {w:'lesson',p:'/ˈlesən/',z:'n. 课；课时',e:'Review the lesson before the quiz.'},
  {w:'textbook sentence',p:'/ˈtekstbʊk ˈsentəns/',z:'n. 课本例句',e:'The textbook sentence gives context.'},
  {w:'context sentence',p:'/ˈkɑːntekst ˈsentəns/',z:'n. 语境例句',e:'A context sentence makes meaning clear.'},
  {w:'word family',p:'/wɜːrd ˈfæməli/',z:'n. 词族',e:'A word family connects related forms.'},
  {w:'part of speech',p:'/pɑːrt əv spiːtʃ/',z:'n. 词性',e:'Check the part of speech.'},
  {w:'collocation',p:'/ˌkɑːləˈkeɪʃən/',z:'n. 词语搭配',e:'Learn a collocation with the word.'},
  {w:'usage',p:'/ˈjuːsɪdʒ/',z:'n. 用法',e:'The example shows common usage.'},
  {w:'definition',p:'/ˌdefəˈnɪʃən/',z:'n. 定义',e:'Read the definition slowly.'},
  {w:'translation note',p:'/trænzˈleɪʃən noʊt/',z:'n. 翻译备注',e:'The translation note explains the phrase.'},
  {w:'pronunciation guide',p:'/prəˌnʌnsiˈeɪʃən ɡaɪd/',z:'n. 发音指南',e:'Use the pronunciation guide.'},
  {w:'listening practice',p:'/ˈlɪsənɪŋ ˈpræktɪs/',z:'n. 听力练习',e:'Listening practice comes before speaking.'},
  {w:'speaking practice',p:'/ˈspiːkɪŋ ˈpræktɪs/',z:'n. 口语练习',e:'Speaking practice builds confidence.'},
  {w:'repeat mode',p:'/rɪˈpiːt moʊd/',z:'n. 重复模式',e:'Repeat mode plays each word twice.'},
  {w:'playback speed',p:'/ˈpleɪbæk spiːd/',z:'n. 播放速度',e:'Adjust playback speed for practice.'},
  {w:'microphone',p:'/ˈmaɪkrəfoʊn/',z:'n. 麦克风',e:'The microphone is not needed for listening.'},
  {w:'pronunciation score',p:'/prəˌnʌnsiˈeɪʃən skɔːr/',z:'n. 发音分数',e:'This version does not use a pronunciation score.'},
  {w:'speech synthesis',p:'/spiːtʃ ˈsɪnθəsɪs/',z:'n. 语音合成',e:'Speech synthesis reads the word.'},
  {w:'voice engine',p:'/vɔɪs ˈendʒɪn/',z:'n. 语音引擎',e:'The voice engine plays clear audio.'},
  {w:'sound button',p:'/saʊnd ˈbʌtən/',z:'n. 发音按钮',e:'Tap the sound button once.'},
  {w:'read and repeat',p:'/riːd ænd rɪˈpiːt/',z:'v. 读并重复',e:'Read and repeat the example.'},
  {w:'daily words',p:'/ˈdeɪli wɜːrdz/',z:'n. 每日单词',e:'Daily words become easier with practice.'},
  {w:'word list',p:'/wɜːrd lɪst/',z:'n. 单词列表',e:'The word list updates each day.'},
  {w:'list item',p:'/lɪst ˈaɪtəm/',z:'n. 列表项',e:'Each list item has a sound button.'},
  {w:'card layout',p:'/kɑːrd ˈleɪaʊt/',z:'n. 卡片布局',e:'The card layout is easy to scan.'},
  {w:'bottom bar',p:'/ˈbɑːtəm bɑːr/',z:'n. 底部操作栏',e:'The bottom bar has two actions.'},
  {w:'settings panel',p:'/ˈsetɪŋz ˈpænəl/',z:'n. 设置面板',e:'Open the settings panel to change words.'},
  {w:'statistics panel',p:'/stəˈtɪstɪks ˈpænəl/',z:'n. 统计面板',e:'The statistics panel shows study days.'},
  {w:'user panel',p:'/ˈjuːzər ˈpænəl/',z:'n. 用户面板',e:'The user panel lets you switch accounts.'},
  {w:'login state',p:'/ˈlɔːɡɪn steɪt/',z:'n. 登录状态',e:'The login state is remembered on this phone.'},
  {w:'guest mode',p:'/ɡest moʊd/',z:'n. 游客模式',e:'Guest mode is disabled in the family app.'},
  {w:'fixed account',p:'/fɪkst əˈkaʊnt/',z:'n. 固定账号',e:'A fixed account keeps the learner list private.'},
  {w:'private access',p:'/ˈpraɪvət ˈækses/',z:'n. 私人访问权限',e:'Private access is limited to two users.'},
  {w:'account security',p:'/əˈkaʊnt sɪˈkjʊrəti/',z:'n. 账号安全',e:'Account security starts with a strong password.'},
  {w:'password hint',p:'/ˈpæswɜːrd hɪnt/',z:'n. 密码提示',e:'Do not show a password hint publicly.'},
  {w:'logout',p:'/ˈlɔːɡaʊt/',z:'n. 退出登录',e:'Use logout before changing users.'},
  {w:'account profile',p:'/əˈkaʊnt ˈproʊfaɪl/',z:'n. 账号资料',e:'The account profile stores only study data.'},
  {w:'separate progress',p:'/ˈsepərət ˈprɑːɡres/',z:'n. 分开的进度',e:'Separate progress keeps practice personal.'},
  {w:'shared phone',p:'/ʃerd foʊn/',z:'n. 共用手机',e:'A shared phone needs account switching.'},
  {w:'personal device',p:'/ˈpɜːrsənəl dɪˈvaɪs/',z:'n. 个人设备',e:'Remember the login on a personal device.'},
  {w:'study privacy',p:'/ˈstʌdi ˈpraɪvəsi/',z:'n. 学习隐私',e:'Study privacy matters to both learners.'},
  {w:'progress privacy',p:'/ˈprɑːɡres ˈpraɪvəsi/',z:'n. 进度隐私',e:'Progress privacy keeps results private.'},
  {w:'private learning',p:'/ˈpraɪvət ˈlɜːrnɪŋ/',z:'n. 私人学习',e:'Private learning lets each person choose a level.'},
  {w:'family learning',p:'/ˈfæməli ˈlɜːrnɪŋ/',z:'n. 家庭学习',e:'Family learning can share a home page.'},
  {w:'parent profile',p:'/ˈperənt ˈproʊfaɪl/',z:'n. 家长资料',e:'The parent profile has its own word bank.'},
  {w:'child profile',p:'/tʃaɪld ˈproʊfaɪl/',z:'n. 孩子资料',e:'The child profile starts with grade eight.'},
  {w:'profile switcher',p:'/ˈproʊfaɪl ˈswɪtʃər/',z:'n. 资料切换器',e:'The profile switcher is in the user menu.'},
  {w:'learning dashboard',p:'/ˈlɜːrnɪŋ ˈdæʃbɔːrd/',z:'n. 学习仪表板',e:'The learning dashboard shows today’s goal.'},
  {w:'today view',p:'/təˈdeɪ vjuː/',z:'n. 今日视图',e:'The today view shows one short task.'},
  {w:'next step',p:'/nekst step/',z:'n. 下一步',e:'The next step is to read aloud.'},
  {w:'one point',p:'/wʌn pɔɪnt/',z:'n. 一个知识点',e:'One point is enough for a focused session.'},
  {w:'small step',p:'/smɔːl step/',z:'n. 小步骤',e:'A small step is easier to keep every day.'},
  {w:'focus lesson',p:'/ˈfoʊkəs ˈlesən/',z:'n. 专注课程',e:'The focus lesson takes ten minutes.'},
  {w:'daily session',p:'/ˈdeɪli ˈseʃən/',z:'n. 每日学习时段',e:'The daily session starts with review.'},
  {w:'study timer',p:'/ˈstʌdi ˈtaɪmər/',z:'n. 学习计时器',e:'The study timer helps you stay focused.'},
  {w:'session complete',p:'/ˈseʃən kəmˈpliːt/',z:'n. 学习完成',e:'The page shows session complete at the end.'},
  {w:'completion mark',p:'/kəmˈpliːʃən mɑːrk/',z:'n. 完成标记',e:'Tap the completion mark after review.'},
  {w:'review later',p:'/rɪˈvjuː ˈleɪtər/',z:'v. 稍后复习',e:'Choose review later if the word is difficult.'},
  {w:'mastered word',p:'/ˈmæstərd wɜːrd/',z:'n. 已掌握单词',e:'A mastered word returns less often.'},
  {w:'difficult word',p:'/ˈdɪfɪkəlt wɜːrd/',z:'n. 难词',e:'A difficult word needs more review.'},
  {w:'easy word',p:'/ˈiːzi wɜːrd/',z:'n. 简单词',e:'An easy word can be reviewed quickly.'},
  {w:'word review',p:'/wɜːrd rɪˈvjuː/',z:'n. 单词复习',e:'Word review is part of the daily plan.'},
  {w:'learning loop',p:'/ˈlɜːrnɪŋ luːp/',z:'n. 学习循环',e:'The learning loop is read, repeat, and review.'},
  {w:'read',p:'/riːd/',z:'v. 阅读；读',e:'Read the word before listening.'},
  {w:'listen',p:'/ˈlɪsən/',z:'v. 听',e:'Listen to the word carefully.'},
  {w:'speak',p:'/spiːk/',z:'v. 说',e:'Speak the word after listening.'},
  {w:'review',p:'/rɪˈvjuː/',z:'v. 复习',e:'Review the word tomorrow.'},
  {w:'practice',p:'/ˈpræktɪs/',z:'v./n. 练习',e:'Practice a little every day.'},
  {w:'improvement',p:'/ɪmˈpruːvmənt/',z:'n. 进步',e:'Small improvement is still progress.'},
  {w:'confidence',p:'/ˈkɑːnfɪdəns/',z:'n. 信心',e:'Practice builds confidence.'},
  {w:'curiosity',p:'/ˌkjʊriˈɑːsəti/',z:'n. 好奇心',e:'Curiosity makes learning interesting.'},
  {w:'motivation',p:'/ˌmoʊtɪˈveɪʃən/',z:'n. 动力',e:'A clear goal gives motivation.'},
  {w:'attention',p:'/əˈtenʃən/',z:'n. 注意力',e:'Short sessions protect attention.'},
  {w:'concentration',p:'/ˌkɑːnsənˈtreɪʃən/',z:'n. 专注力',e:'Quiet space helps concentration.'},
  {w:'memory',p:'/ˈmeməri/',z:'n. 记忆',e:'Examples help memory.'},
  {w:'recall practice',p:'/rɪˈkɔːl ˈpræktɪs/',z:'n. 回忆练习',e:'Recall practice checks what you know.'},
  {w:'active recall',p:'/ˈæktɪv rɪˈkɔːl/',z:'n. 主动回忆',e:'Active recall is stronger than rereading.'},
  {w:'retrieval practice',p:'/rɪˈtriːvəl ˈpræktɪs/',z:'n. 检索练习',e:'Retrieval practice makes memory stronger.'},
  {w:'learning science',p:'/ˈlɜːrnɪŋ ˈsaɪəns/',z:'n. 学习科学',e:'Learning science supports better habits.'},
  {w:'study habit',p:'/ˈstʌdi ˈhæbɪt/',z:'n. 学习习惯',e:'A study habit grows through repetition.'},
  {w:'daily routine',p:'/ˈdeɪli ruːˈtiːn/',z:'n. 日常安排',e:'Put review into your daily routine.'},
  {w:'morning review',p:'/ˈmɔːrnɪŋ rɪˈvjuː/',z:'n. 早晨复习',e:'A morning review can be very short.'},
  {w:'evening review',p:'/ˈiːvnɪŋ rɪˈvjuː/',z:'n. 晚间复习',e:'An evening review closes the day.'},
  {w:'weekly review',p:'/ˈwiːkli rɪˈvjuː/',z:'n. 每周复习',e:'Weekly review shows the bigger picture.'},
  {w:'monthly review',p:'/ˈmʌnθli rɪˈvjuː/',z:'n. 每月复习',e:'Monthly review helps set the next goal.'},
  {w:'learning report',p:'/ˈlɜːrnɪŋ rɪˈpɔːrt/',z:'n. 学习报告',e:'The learning report summarizes the month.'},
  {w:'progress summary',p:'/ˈprɑːɡres ˈsʌməri/',z:'n. 进度摘要',e:'The progress summary is easy to read.'},
  {w:'achievement',p:'/əˈtʃiːvmənt/',z:'n. 成就',e:'Finishing a week is an achievement.'},
  {w:'celebration',p:'/ˌseləˈbreɪʃən/',z:'n. 庆祝',e:'A small celebration keeps learning fun.'},
  {w:'encouragement',p:'/ɪnˈkɜːrɪdʒmənt/',z:'n. 鼓励',e:'A kind message gives encouragement.'},
  {w:'support',p:'/səˈpɔːrt/',z:'n./v. 支持',e:'The app gives simple support.'},
  {w:'reminder',p:'/rɪˈmaɪndər/',z:'n. 提醒',e:'A reminder can start the daily session.'},
  {w:'notification',p:'/ˌnoʊtɪfɪˈkeɪʃən/',z:'n. 通知',e:'Turn off the notification during focus time.'},
  {w:'quiet mode',p:'/ˈkwaɪət moʊd/',z:'n. 静音模式',e:'Quiet mode removes distractions.'},
  {w:'distraction',p:'/dɪˈstrækʃən/',z:'n. 干扰',e:'Put the phone away to avoid distraction.'},
  {w:'break reminder',p:'/breɪk rɪˈmaɪndər/',z:'n. 休息提醒',e:'A break reminder protects your eyes.'},
  {w:'healthy pace',p:'/ˈhelθi peɪs/',z:'n. 健康节奏',e:'Choose a healthy pace for long-term learning.'},
  {w:'long-term goal',p:'/ˌlɔːŋ ˈtɜːrm ɡoʊl/',z:'n. 长期目标',e:'A long-term goal needs small steps.'},
  {w:'short-term goal',p:'/ˌʃɔːrt ˈtɜːrm ɡoʊl/',z:'n. 短期目标',e:'Set a short-term goal for today.'},
  {w:'weekly target',p:'/ˈwiːkli ˈtɑːrɡɪt/',z:'n. 每周目标',e:'The weekly target is easy to see.'},
  {w:'learning choice',p:'/ˈlɜːrnɪŋ tʃɔɪs/',z:'n. 学习选择',e:'Learning choice keeps the app flexible.'},
  {w:'free choice',p:'/friː tʃɔɪs/',z:'n. 自由选择',e:'You can make a free choice of word bank.'},
  {w:'custom list',p:'/ˈkʌstəm lɪst/',z:'n. 自定义列表',e:'A custom list can hold your own words.'},
  {w:'favorite',p:'/ˈfeɪvərɪt/',z:'n./adj. 收藏；喜欢的',e:'Save a favorite word for later.'},
  {w:'bookmark word',p:'/ˈbʊkmɑːrk wɜːrd/',z:'v. 收藏单词',e:'Bookmark a word you want to revisit.'},
  {w:'personal vocabulary',p:'/ˈpɜːrsənəl vəˈkæbjəleri/',z:'n. 个人词汇',e:'Personal vocabulary grows with reading.'},
  {w:'word note',p:'/wɜːrd noʊt/',z:'n. 单词笔记',e:'Add a word note in your notebook.'},
  {w:'memory hint',p:'/ˈmeməri hɪnt/',z:'n. 记忆提示',e:'Write a memory hint in your own words.'},
  {w:'picture hint',p:'/ˈpɪktʃər hɪnt/',z:'n. 图片提示',e:'A picture hint can make a word memorable.'},
  {w:'sound hint',p:'/saʊnd hɪnt/',z:'n. 声音提示',e:'Use the sound hint before reading.'},
  {w:'context hint',p:'/ˈkɑːntekst hɪnt/',z:'n. 语境提示',e:'The context hint explains the phrase.'},
  {w:'example bank',p:'/ɪɡˈzæmpəl bæŋk/',z:'n. 例句库',e:'The example bank stores useful sentences.'},
  {w:'sentence pattern',p:'/ˈsentəns ˈpætərn/',z:'n. 句型',e:'Notice the sentence pattern.'},
  {w:'grammar point',p:'/ˈɡræmər pɔɪnt/',z:'n. 语法点',e:'The sentence includes one grammar point.'},
  {w:'reading context',p:'/ˈriːdɪŋ ˈkɑːntekst/',z:'n. 阅读语境',e:'Reading context makes a new word clearer.'},
  {w:'speaking context',p:'/ˈspiːkɪŋ ˈkɑːntekst/',z:'n. 口语语境',e:'Speaking context helps you use the phrase.'},
  {w:'translation pair',p:'/trænzˈleɪʃən per/',z:'n. 翻译对照',e:'The translation pair shows both languages.'},
  {w:'language pair',p:'/ˈlæŋɡwɪdʒ per/',z:'n. 语言对',e:'Choose a language pair for study.'},
  {w:'English word',p:'/ˈɪŋɡlɪʃ wɜːrd/',z:'n. 英语单词',e:'One English word can have several meanings.'},
  {w:'Chinese meaning',p:'/ˈtʃaɪniːz ˈmiːnɪŋ/',z:'n. 中文含义',e:'Read the Chinese meaning after trying.'},
  {w:'word pronunciation',p:'/wɜːrd prəˌnʌnsiˈeɪʃən/',z:'n. 单词发音',e:'Word pronunciation becomes easier with listening.'},
  {w:'example audio',p:'/ɪɡˈzæmpəl ˈɔːdioʊ/',z:'n. 例句音频',e:'Example audio helps with rhythm.'},
  {w:'reading aloud',p:'/ˈriːdɪŋ əˈlaʊd/',z:'n. 朗读',e:'Reading aloud improves confidence.'},
  {w:'repeat after me',p:'/rɪˈpiːt ˈæftər miː/',z:'phr. 跟我重复',e:'Listen and repeat after me.'},
  {w:'listen again',p:'/ˈlɪsən əˈɡen/',z:'phr. 再听一次',e:'Tap listen again when needed.'},
  {w:'speak slowly',p:'/spiːk ˈsloʊli/',z:'phr. 慢慢说',e:'Speak slowly and clearly.'},
  {w:'clear audio',p:'/klɪr ˈɔːdioʊ/',z:'n. 清晰音频',e:'Clear audio makes practice comfortable.'},
  {w:'learning feedback',p:'/ˈlɜːrnɪŋ ˈfiːdbæk/',z:'n. 学习反馈',e:'Learning feedback shows what to try next.'},
  {w:'instant feedback',p:'/ˈɪnstənt ˈfiːdbæk/',z:'n. 即时反馈',e:'Instant feedback is useful after an answer.'},
  {w:'delayed review',p:'/dɪˈleɪd rɪˈvjuː/',z:'n. 延迟复习',e:'Delayed review strengthens memory.'},
  {w:'review interval',p:'/rɪˈvjuː ˈɪntərvəl/',z:'n. 复习间隔',e:'The review interval grows over time.'},
  {w:'memory strength',p:'/ˈmeməri streŋθ/',z:'n. 记忆强度',e:'Memory strength changes with practice.'},
  {w:'knowledge check',p:'/ˈnɑːlɪdʒ tʃek/',z:'n. 知识检查',e:'A knowledge check takes one minute.'},
  {w:'quick quiz',p:'/kwɪk kwɪz/',z:'n. 快速小测',e:'Take a quick quiz after reading.'},
  {w:'choice question',p:'/tʃɔɪs ˈkwestʃən/',z:'n. 选择题',e:'The choice question checks meaning.'},
  {w:'fill in the blank',p:'/fɪl ɪn ðə blæŋk/',z:'phr. 填空',e:'Fill in the blank with the right word.'},
  {w:'matching task',p:'/ˈmætʃɪŋ tæsk/',z:'n. 匹配任务',e:'The matching task connects words and meanings.'},
  {w:'review result',p:'/rɪˈvjuː rɪˈzʌlt/',z:'n. 复习结果',e:'The review result updates the progress.'},
  {w:'mastery level',p:'/ˈmæstəri ˈlevəl/',z:'n. 掌握等级',e:'The mastery level changes after practice.'},
  {w:'learning status',p:'/ˈlɜːrnɪŋ ˈsteɪtəs/',z:'n. 学习状态',e:'The learning status is saved locally.'},
  {w:'study record',p:'/ˈstʌdi ˈrekərd/',z:'n. 学习记录',e:'The study record shows your daily work.'},
  {w:'word progress',p:'/wɜːrd ˈprɑːɡres/',z:'n. 单词进度',e:'Word progress is separate for each account.'},
  {w:'review plan',p:'/rɪˈvjuː plæn/',z:'n. 复习计划',e:'The review plan chooses difficult words.'},
  {w:'practice plan',p:'/ˈpræktɪs plæn/',z:'n. 练习计划',e:'The practice plan starts with five words.'},
  {w:'daily practice',p:'/ˈdeɪli ˈpræktɪs/',z:'n. 每日练习',e:'Daily practice builds a strong habit.'},
  {w:'weekly practice',p:'/ˈwiːkli ˈpræktɪs/',z:'n. 每周练习',e:'Weekly practice checks the whole unit.'},
  {w:'subject vocabulary',p:'/ˈsʌbdʒekt vəˈkæbjəleri/',z:'n. 学科词汇',e:'Subject vocabulary helps with science reading.'},
  {w:'technology vocabulary',p:'/tekˈnɑːlədʒi vəˈkæbjəleri/',z:'n. 科技词汇',e:'Technology vocabulary changes quickly.'},
  {w:'AI term',p:'/eɪ aɪ tɜːrm/',z:'n. AI 术语',e:'Learn one AI term at a time.'},
  {w:'technical term',p:'/ˈteknɪkəl tɜːrm/',z:'n. 技术术语',e:'A technical term needs a clear example.'},
  {w:'plain language',p:'/pleɪn ˈlæŋɡwɪdʒ/',z:'n. 通俗语言',e:'Explain the term in plain language.'},
  {w:'simple explanation',p:'/ˈsɪmpəl ˌekspləˈneɪʃən/',z:'n. 简单解释',e:'A simple explanation is easier to remember.'},
  {w:'technical example',p:'/ˈteknɪkəl ɪɡˈzæmpəl/',z:'n. 技术例子',e:'Use a technical example to show the idea.'},
  {w:'concept map',p:'/ˈkɑːnsept mæp/',z:'n. 概念图',e:'A concept map connects related terms.'},
  {w:'related word',p:'/rɪˈleɪtɪd wɜːrd/',z:'n. 相关词',e:'Review a related word together.'},
  {w:'word connection',p:'/wɜːrd kəˈnekʃən/',z:'n. 单词联系',e:'A word connection makes recall easier.'},
  {w:'term group',p:'/tɜːrm ɡruːp/',z:'n. 术语组',e:'The term group covers data and safety.'},
  {w:'topic group',p:'/ˈtɑːpɪk ɡruːp/',z:'n. 主题组',e:'Choose a topic group from the menu.'},
  {w:'beginner list',p:'/bɪˈɡɪnər lɪst/',z:'n. 初学者列表',e:'The beginner list uses common words.'},
  {w:'advanced list',p:'/ədˈvænst lɪst/',z:'n. 进阶列表',e:'The advanced list includes longer phrases.'},
  {w:'core term',p:'/kɔːr tɜːrm/',z:'n. 核心术语',e:'Start with the core term.'},
  {w:'extended term',p:'/ɪkˈstendɪd tɜːrm/',z:'n. 拓展术语',e:'Add an extended term after the core one.'},
  {w:'word set',p:'/wɜːrd set/',z:'n. 词组',e:'This word set has one hundred items.'},
  {w:'first batch',p:'/fɜːrst bætʃ/',z:'n. 第一批',e:'The first batch is ready to study.'},
  {w:'next batch',p:'/nekst bætʃ/',z:'n. 下一批',e:'The next batch appears tomorrow.'},
  {w:'large vocabulary',p:'/lɑːrdʒ vəˈkæbjəleri/',z:'n. 大词库',e:'A large vocabulary gives more choices.'},
  {w:'word coverage',p:'/wɜːrd ˈkʌvərɪdʒ/',z:'n. 词汇覆盖',e:'The list improves word coverage.'},
  {w:'textbook coverage',p:'/ˈtekstbʊk ˈkʌvərɪdʒ/',z:'n. 教材覆盖',e:'Textbook coverage will be checked later.'},
  {w:'version check',p:'/ˈvɜːrʒən tʃek/',z:'n. 版本检查',e:'Do a version check when the book arrives.'},
  {w:'content update',p:'/ˈkɑːntent ʌpˈdeɪt/',z:'n. 内容更新',e:'The content update adds new words.'},
  {w:'data update',p:'/ˈdeɪtə ʌpˈdeɪt/',z:'n. 数据更新',e:'The data update does not erase progress.'},
  {w:'safe update',p:'/seɪf ʌpˈdeɪt/',z:'n. 安全更新',e:'A safe update keeps the old list available.'},
  {w:'content source',p:'/ˈkɑːntent sɔːrs/',z:'n. 内容来源',e:'Record the content source for review.'},
  {w:'source note',p:'/sɔːrs noʊt/',z:'n. 来源备注',e:'The source note says which book was used.'},
  {w:'temporary version',p:'/ˈtempəreri ˈvɜːrʒən/',z:'n. 临时版本',e:'This is a temporary version for early practice.'},
  {w:'verified version',p:'/ˈverɪfaɪd ˈvɜːrʒən/',z:'n. 已核对版本',e:'The verified version will follow the real book.'},
  {w:'content replacement',p:'/ˈkɑːntent rɪˈpleɪsmənt/',z:'n. 内容替换',e:'Content replacement should not reset progress.'},
  {w:'data compatibility',p:'/ˈdeɪtə kəmˌpætəˈbɪləti/',z:'n. 数据兼容性',e:'Data compatibility protects old records.'},
  {w:'migration safety',p:'/maɪˈɡreɪʃən ˈseɪfti/',z:'n. 迁移安全',e:'Migration safety comes before new features.'},
  {w:'release checklist',p:'/rɪˈliːs ˈtʃeklɪst/',z:'n. 发布检查清单',e:'The release checklist includes a backup.'},
  {w:'final check',p:'/ˈfaɪnəl tʃek/',z:'n. 最终检查',e:'Do a final check before sharing.'},
  {w:'ready to learn',p:'/ˈredi tə lɜːrn/',z:'phr. 准备学习',e:'The word bank is ready to learn.'},
  {w:'keep learning',p:'/kiːp ˈlɜːrnɪŋ/',z:'phr. 继续学习',e:'Keep learning one small step at a time.'}
];

// 第一版控制在“现有 98 词 + 新增 102 词 = 200 词”，后续再按主题继续扩充。
AI_EXTRA = AI_EXTRA.filter(function(item, index, items) {
  return items.findIndex(function(candidate) {
    return candidate.w.toLowerCase() === item.w.toLowerCase();
  }) === index;
}).slice(0, 102);

if (typeof module !== 'undefined') module.exports = AI_EXTRA;
