var GRADE8_TERM1_EXTRA = [
  {w:'anyone',p:'/ˈeniwʌn/',z:'pron. 任何人',e:'Did anyone go with you?'},
  {w:'anywhere',p:'/ˈeniwer/',z:'adv. 任何地方',e:'We can go anywhere after lunch.'},
  {w:'wonderful',p:'/ˈwʌndərfəl/',z:'adj. 精彩的',e:'We had a wonderful time.'},
  {w:'few',p:'/fjuː/',z:'adj./pron. 不多；少数',e:'There are a few new students.'},
  {w:'quite',p:'/kwaɪt/',z:'adv. 相当；十分',e:'The food was quite good.'},
  {w:'most',p:'/moʊst/',z:'adj./pron. 大多数',e:'Most students like music.'},
  {w:'something',p:'/ˈsʌmθɪŋ/',z:'pron. 某事；某物',e:'There is something special here.'},
  {w:'nothing',p:'/ˈnʌθɪŋ/',z:'pron. 没有什么',e:'There is nothing in the box.'},
  {w:'everyone',p:'/ˈevriwʌn/',z:'pron. 每人',e:'Everyone enjoyed the trip.'},
  {w:'myself',p:'/maɪˈself/',z:'pron. 我自己',e:'I made it myself.'},
  {w:'yourself',p:'/jɔːrˈself/',z:'pron. 你自己',e:'Did you enjoy yourself?'},
  {w:'hen',p:'/hen/',z:'n. 母鸡',e:'The hen laid an egg.'},
  {w:'pig',p:'/pɪɡ/',z:'n. 猪',e:'The farmer keeps a pig.'},
  {w:'diary',p:'/ˈdaɪəri/',z:'n. 日记',e:'She writes in her diary every night.'},
  {w:'activity',p:'/ækˈtɪvəti/',z:'n. 活动',e:'The school planned a fun activity.'},
  {w:'programmer',p:'/ˈproʊɡræmər/',z:'n. 程序员',e:'He wants to become a programmer.'},
  {w:'decide',p:'/dɪˈsaɪd/',z:'v. 决定',e:'We decided to visit the museum.'},
  {w:'try',p:'/traɪ/',z:'v. 尝试；设法',e:'Try to remember the new words.'},
  {w:'bicycle',p:'/ˈbaɪsɪkəl/',z:'n. 自行车',e:'He rides a bicycle to school.'},
  {w:'building',p:'/ˈbɪldɪŋ/',z:'n. 建筑物',e:'The building is near the river.'},
  {w:'trader',p:'/ˈtreɪdər/',z:'n. 商人',e:'The trader sold fruit at the market.'},
  {w:'wonder',p:'/ˈwʌndər/',z:'v./n. 想知道；奇迹',e:'I wonder what happened.'},
  {w:'difference',p:'/ˈdɪfərəns/',z:'n. 差别',e:'Can you find the difference?'},
  {w:'top',p:'/tɑːp/',z:'n. 顶部；最高处',e:'We reached the top of the hill.'},
  {w:'wait',p:'/weɪt/',z:'v. 等待',e:'Please wait for me.'},
  {w:'umbrella',p:'/ʌmˈbrelə/',z:'n. 雨伞',e:'Take an umbrella; it may rain.'},
  {w:'wet',p:'/wet/',z:'adj. 湿的',e:'My shoes are wet.'},
  {w:'below',p:'/bɪˈloʊ/',z:'prep./adv. 在下面',e:'The village lies below the mountain.'},
  {w:'enough',p:'/ɪˈnʌf/',z:'adj./adv. 足够的',e:'We have enough food for everyone.'},
  {w:'hungry',p:'/ˈhʌŋɡri/',z:'adj. 饥饿的',e:'I was hungry after the walk.'},
  {w:'as',p:'/æz/',z:'conj./prep. 像；如同',e:'As a child, she loved animals.'},
  {w:'dislike',p:'/dɪsˈlaɪk/',z:'v./n. 不喜欢',e:'I dislike waiting in long lines.'},
  {w:'because of',p:'/bɪˈkɔːz əv/',z:'prep. 因为',e:'The game stopped because of rain.'},
  {w:'hill',p:'/hɪl/',z:'n. 小山',e:'They walked up the hill.'},
  {w:'duck',p:'/dʌk/',z:'n. 鸭子',e:'A duck swam across the lake.'},
  {w:'housework',p:'/ˈhaʊswɜːrk/',z:'n. 家务劳动',e:'I help with housework at home.'},
  {w:'hardly',p:'/ˈhɑːrdli/',z:'adv. 几乎不',e:'I hardly watch television.'},
  {w:'ever',p:'/ˈevər/',z:'adv. 曾经',e:'Have you ever tried skating?'},
  {w:'once',p:'/wʌns/',z:'adv. 一次；曾经',e:'I visit my grandparents once a week.'},
  {w:'twice',p:'/twaɪs/',z:'adv. 两次',e:'She practices twice a day.'},
  {w:'program',p:'/ˈproʊɡræm/',z:'n. 节目；程序',e:'This program is useful for students.'},
  {w:'full',p:'/fʊl/',z:'adj. 忙的；满的',e:'My weekend is full of activities.'},
  {w:'maybe',p:'/ˈmeɪbi/',z:'adv. 可能；大概',e:'Maybe we can meet tomorrow.'},
  {w:'least',p:'/liːst/',z:'adv./adj. 最少；最小',e:'At least read one page.'},
  {w:'health',p:'/helθ/',z:'n. 健康',e:'Exercise is good for your health.'},
  {w:'result',p:'/rɪˈzʌlt/',z:'n. 结果',e:'The result surprised us.'},
  {w:'percent',p:'/pərˈsent/',z:'n. 百分之',e:'Thirty percent of students walk to school.'},
  {w:'online',p:'/ˌɑːnˈlaɪn/',z:'adj./adv. 在线的',e:'The class is available online.'},
  {w:'although',p:'/ɔːlˈðoʊ/',z:'conj. 虽然',e:'Although it rained, we went out.'},
  {w:'through',p:'/θruː/',z:'prep. 以；穿过',e:'We learned through practice.'},
  {w:'mind',p:'/maɪnd/',z:'n. 头脑；介意',e:'Would you mind opening the window?'},
  {w:'body',p:'/ˈbɑːdi/',z:'n. 身体',e:'Exercise keeps your body strong.'},
  {w:'such',p:'/sʌtʃ/',z:'adj. 这样的；如此的',e:'It was such a beautiful day.'},
  {w:'together',p:'/təˈɡeðər/',z:'adv. 一起',e:'Let us study together.'},
  {w:'die',p:'/daɪ/',z:'v. 消失；死亡',e:'Plants may die without water.'},
  {w:'writer',p:'/ˈraɪtər/',z:'n. 作者；作家',e:'The writer tells a warm story.'},
  {w:'outgoing',p:'/ˈaʊtɡoʊɪŋ/',z:'adj. 外向的',e:'She is outgoing and friendly.'},
  {w:'better',p:'/ˈbetər/',z:'adj./adv. 更好的；更好地',e:'Practice helps me speak better.'},
  {w:'loudly',p:'/ˈlaʊdli/',z:'adv. 喧闹地',e:'Please do not talk loudly in class.'},
  {w:'quietly',p:'/ˈkwaɪətli/',z:'adv. 安静地',e:'The baby slept quietly.'},
  {w:'hard-working',p:'/ˌhɑːrd ˈwɜːrkɪŋ/',z:'adj. 工作努力的',e:'She is a hard-working student.'},
  {w:'competition',p:'/ˌkɑːmpəˈtɪʃən/',z:'n. 比赛',e:'He joined a reading competition.'},
  {w:'fantastic',p:'/fænˈtæstɪk/',z:'adj. 极好的',e:'You did a fantastic job.'},
  {w:'clearly',p:'/ˈklɪrli/',z:'adv. 清楚地',e:'Please speak clearly.'},
  {w:'win',p:'/wɪn/',z:'v. 获胜；赢得',e:'Our team hopes to win.'},
  {w:'though',p:'/ðoʊ/',z:'conj./adv. 虽然；不过',e:'It was difficult, though I enjoyed it.'},
  {w:'talented',p:'/ˈtæləntɪd/',z:'adj. 有才能的',e:'The talented girl plays the piano.'},
  {w:'care',p:'/ker/',z:'v. 在意；关心',e:'Good friends care about each other.'},
  {w:'truly',p:'/ˈtruːli/',z:'adv. 真正；确实',e:'She truly wants to help.'},
  {w:'necessary',p:'/ˈnesəseri/',z:'adj. 必需的',e:'Sleep is necessary for health.'},
  {w:'both',p:'/boʊθ/',z:'adj./pron. 两个；两个都',e:'Both answers are correct.'},
  {w:'should',p:'/ʃʊd/',z:'modal v. 应该',e:'You should review every day.'},
  {w:'reach',p:'/riːtʃ/',z:'v. 到达；伸手',e:'We reached the station at noon.'},
  {w:'touch',p:'/tʌtʃ/',z:'v. 感动；触摸',e:'The story touched my heart.'},
  {w:'heart',p:'/hɑːrt/',z:'n. 内心；心脏',e:'She spoke from her heart.'},
  {w:'fact',p:'/fækt/',z:'n. 事实',e:'That is an interesting fact.'},
  {w:'break',p:'/breɪk/',z:'v./n. 打破；休息',e:'Let us take a short break.'},
  {w:'laugh',p:'/læf/',z:'v./n. 笑',e:'The joke made everyone laugh.'},
  {w:'similar',p:'/ˈsɪmələr/',z:'adj. 相似的',e:'The two pictures are similar.'},
  {w:'information',p:'/ˌɪnfərˈmeɪʃən/',z:'n. 信息',e:'The website gives useful information.'},
  {w:'theater',p:'/ˈθiːətər/',z:'n. 戏院；剧场',e:'The theater has comfortable seats.'},
  {w:'comfortable',p:'/ˈkʌmfərtəbəl/',z:'adj. 舒服的',e:'This chair is comfortable.'},
  {w:'seat',p:'/siːt/',z:'n. 座位',e:'Please take your seat.'},
  {w:'screen',p:'/skriːn/',z:'n. 屏幕',e:'The movie looks clear on the screen.'},
  {w:'close',p:'/kloʊs/',z:'adj. 接近的',e:'The cinema is close to my home.'},
  {w:'ticket',p:'/ˈtɪkɪt/',z:'n. 票；入场券',e:'I bought two movie tickets.'},
  {w:'worst',p:'/wɜːrst/',z:'adj. 最差的',e:'That was the worst service.'},
  {w:'cheaply',p:'/ˈtʃiːpli/',z:'adv. 便宜地',e:'We can buy the tickets cheaply online.'},
  {w:'song',p:'/sɔːŋ/',z:'n. 歌曲',e:'This song is popular with students.'},
  {w:'choose',p:'/tʃuːz/',z:'v. 选择',e:'Choose a movie you like.'},
  {w:'carefully',p:'/ˈkerfəli/',z:'adv. 仔细地',e:'Read the question carefully.'},
  {w:'reporter',p:'/rɪˈpɔːrtər/',z:'n. 记者',e:'The reporter asked a question.'},
  {w:'fresh',p:'/freʃ/',z:'adj. 新鲜的',e:'The vegetables are fresh.'},
  {w:'comfortably',p:'/ˈkʌmfərtəbli/',z:'adv. 舒服地',e:'We sat comfortably in the room.'},
  {w:'worse',p:'/wɜːrs/',z:'adj./adv. 更差的',e:'The weather became worse.'},
  {w:'service',p:'/ˈsɜːrvɪs/',z:'n. 服务',e:'The hotel offers good service.'},
  {w:'pretty',p:'/ˈprɪti/',z:'adv. 相当；漂亮的',e:'The park is pretty beautiful.'},
  {w:'menu',p:'/ˈmenjuː/',z:'n. 菜单',e:'May I see the menu?'},
  {w:'act',p:'/ækt/',z:'v. 表演；行动',e:'He can act very well.'},
  {w:'meal',p:'/miːl/',z:'n. 一餐',e:'Breakfast is an important meal.'},
  {w:'creative',p:'/kriˈeɪtɪv/',z:'adj. 有创造力的',e:'She has a creative idea.'},
  {w:'performer',p:'/pərˈfɔːrmər/',z:'n. 表演者',e:'The performer made us laugh.'},
  {w:'talent',p:'/ˈtælənt/',z:'n. 才能',e:'He has a talent for music.'},
  {w:'common',p:'/ˈkɑːmən/',z:'adj. 普通的；常见的',e:'This is a common mistake.'},
  {w:'role',p:'/roʊl/',z:'n. 作用；角色',e:'She played the main role.'},
  {w:'winner',p:'/ˈwɪnər/',z:'n. 获胜者',e:'The winner received a prize.'},
  {w:'prize',p:'/praɪz/',z:'n. 奖品；奖金',e:'He won first prize.'},
  {w:'everybody',p:'/ˈevribɑːdi/',z:'pron. 每人',e:'Everybody had a good time.'},
  {w:'example',p:'/ɪɡˈzæmpəl/',z:'n. 例子',e:'This sentence is a good example.'},
  {w:'poor',p:'/pʊr/',z:'adj. 贫穷的；差的',e:'The service was poor.'},
  {w:'seriously',p:'/ˈsɪriəsli/',z:'adv. 严重地；认真地',e:'Take the advice seriously.'},
  {w:'give',p:'/ɡɪv/',z:'v. 提供；给',e:'The show gives us a chance to learn.'},
  {w:'sitcom',p:'/ˈsɪtkɑːm/',z:'n. 情景喜剧',e:'My family watches a sitcom together.'},
  {w:'news',p:'/nuːz/',z:'n. 新闻节目',e:'I watched the news last night.'},
  {w:'educational',p:'/ˌedʒuˈkeɪʃənəl/',z:'adj. 教育的',e:'The program is both fun and educational.'},
  {w:'plan',p:'/plæn/',z:'v./n. 计划',e:'I plan to read this weekend.'},
  {w:'hope',p:'/hoʊp/',z:'v./n. 希望',e:'I hope to visit Beijing one day.'},
  {w:'discussion',p:'/dɪˈskʌʃən/',z:'n. 讨论',e:'We had a discussion about the show.'},
  {w:'stand',p:'/stænd/',z:'v. 忍受；站立',e:'I cannot stand noisy programs.'},
  {w:'happen',p:'/ˈhæpən/',z:'v. 发生',e:'What happened yesterday?'},
  {w:'expect',p:'/ɪkˈspekt/',z:'v. 预料；期待',e:'I expect to learn something new.'},
  {w:'joke',p:'/dʒoʊk/',z:'n. 笑话',e:'He told a funny joke.'},
  {w:'meaningless',p:'/ˈmiːnɪŋləs/',z:'adj. 毫无意义的',e:'The activity felt meaningless.'},
  {w:'action',p:'/ˈækʃən/',z:'n. 动作片；行动',e:'He enjoys action movies.'},
  {w:'cartoon',p:'/kɑːrˈtuːn/',z:'n. 动画片',e:'The cartoon is popular with children.'},
  {w:'culture',p:'/ˈkʌltʃər/',z:'n. 文化',e:'The show teaches us about culture.'},
  {w:'famous',p:'/ˈfeɪməs/',z:'adj. 著名的',e:'The actor is famous around the world.'},
  {w:'appear',p:'/əˈpɪr/',z:'v. 出现',e:'A rainbow appeared after the rain.'},
  {w:'become',p:'/bɪˈkʌm/',z:'v. 变成',e:'She wants to become a writer.'},
  {w:'rich',p:'/rɪtʃ/',z:'adj. 富有的；丰富的',e:'The story is rich in detail.'},
  {w:'successful',p:'/səkˈsesfəl/',z:'adj. 成功的',e:'Hard work makes a successful student.'},
  {w:'might',p:'/maɪt/',z:'modal v. 可能',e:'It might rain later.'},
  {w:'reason',p:'/ˈriːzən/',z:'n. 原因',e:'What is the reason for your choice?'},
  {w:'main',p:'/meɪn/',z:'adj. 主要的',e:'The main character is brave.'},
  {w:'ready',p:'/ˈredi/',z:'adj. 准备好的',e:'Are you ready for the test?'},
  {w:'army',p:'/ˈɑːrmi/',z:'n. 陆军；军队',e:'The story is about a young army officer.'},
  {w:'enjoyable',p:'/ɪnˈdʒɔɪəbəl/',z:'adj. 愉快的',e:'The trip was enjoyable.'},
  {w:'grow up',p:'/ɡroʊ ʌp/',z:'长大；成长',e:'What do you want to be when you grow up?'},
  {w:'computer programmer',p:'/kəmˈpjuːtər ˈproʊɡræmər/',z:'n. 计算机程序设计员',e:'He wants to be a computer programmer.'},
  {w:'cook',p:'/kʊk/',z:'n. 厨师；v. 烹饪',e:'My uncle works as a cook.'},
  {w:'doctor',p:'/ˈdɑːktər/',z:'n. 医生',e:'She hopes to become a doctor.'},
  {w:'engineer',p:'/ˌendʒəˈnɪr/',z:'n. 工程师',e:'His sister is an engineer.'},
  {w:'violinist',p:'/ˌvaɪəˈlɪnɪst/',z:'n. 小提琴手',e:'The violinist practiced every morning.'},
  {w:'pianist',p:'/ˈpiːənɪst/',z:'n. 钢琴家',e:'The pianist played beautifully.'},
  {w:'scientist',p:'/ˈsaɪəntɪst/',z:'n. 科学家',e:'The scientist studies plants.'},
  {w:'pilot',p:'/ˈpaɪlət/',z:'n. 飞行员',e:'The pilot welcomed the passengers.'},
  {w:'college',p:'/ˈkɑːlɪdʒ/',z:'n. 大学',e:'She plans to go to college.'},
  {w:'education',p:'/ˌedʒuˈkeɪʃən/',z:'n. 教育',e:'Education can change a life.'},
  {w:'medicine',p:'/ˈmedɪsɪn/',z:'n. 药；医学',e:'He wants to study medicine.'},
  {w:'article',p:'/ˈɑːrtɪkəl/',z:'n. 文章；物品',e:'I read an article about space.'},
  {w:'send',p:'/send/',z:'v. 邮寄；发送',e:'Please send me the picture.'},
  {w:'foreign',p:'/ˈfɔːrən/',z:'adj. 外国的',e:'She enjoys learning a foreign language.'},
  {w:'promise',p:'/ˈprɑːmɪs/',z:'v./n. 许诺',e:'I promise to work hard.'},
  {w:'beginning',p:'/bɪˈɡɪnɪŋ/',z:'n. 开头；开始',e:'The beginning of the story is funny.'},
  {w:'improve',p:'/ɪmˈpruːv/',z:'v. 改进；提高',e:'Reading can improve your English.'},
  {w:'physical',p:'/ˈfɪzɪkəl/',z:'adj. 身体的',e:'Physical exercise is good for us.'},
  {w:'themselves',p:'/ðəmˈselvz/',z:'pron. 他/她/它们自己',e:'They made the model themselves.'},
  {w:'relationship',p:'/rɪˈleɪʃənʃɪp/',z:'n. 关系',e:'Trust is important in a relationship.'},
  {w:'hobby',p:'/ˈhɑːbi/',z:'n. 业余爱好',e:'Reading is my favorite hobby.'},
  {w:'weekly',p:'/ˈwiːkli/',z:'adj./adv. 每周的',e:'We have a weekly class meeting.'},
  {w:'schoolwork',p:'/ˈskuːlwɜːrk/',z:'n. 学校作业',e:'Finish your schoolwork before dinner.'},
  {w:'resolution',p:'/ˌrezəˈluːʃən/',z:'n. 决心；决定',e:'My resolution is to read more.'},
  {w:'foreign language',p:'/ˈfɔːrən ˈlæŋɡwɪdʒ/',z:'n. 外语',e:'English is a foreign language for many learners.'},
  {w:'take up',p:'/teɪk ʌp/',z:'开始做；学着做',e:'She plans to take up painting.'},
  {w:'be able to',p:'/bi ˈeɪbəl tə/',z:'能够',e:'You will be able to swim soon.'},
  {w:'make sure',p:'/meɪk ʃʊr/',z:'确保；查明',e:'Make sure you have your notebook.'},
  {w:'write down',p:'/raɪt daʊn/',z:'写下；记录',e:'Write down the new words.'},
  {w:'take notes',p:'/teɪk noʊts/',z:'记笔记',e:'Take notes during the lesson.'},
  {w:'keep a diary',p:'/kiːp ə ˈdaɪəri/',z:'记日记',e:'She likes to keep a diary.'},
  {w:'stay at home',p:'/steɪ æt hoʊm/',z:'待在家里',e:'We stayed at home because of rain.'},
  {w:'go on vacation',p:'/ɡoʊ ɑːn veɪˈkeɪʃən/',z:'去度假',e:'They plan to go on vacation.'},
  {w:'feel like',p:'/fiːl laɪk/',z:'给……的感觉；想要',e:'I feel like eating noodles.'},
  {w:'of course',p:'/əv kɔːrs/',z:'当然；自然',e:'Of course you can join us.'},
  {w:'at least',p:'/æt liːst/',z:'至少',e:'Read at least ten words today.'},
  {w:'such as',p:'/sʌtʃ æz/',z:'例如',e:'I like fruit such as apples and pears.'},
  {w:'more than',p:'/mɔːr ðæn/',z:'多于',e:'More than half the class joined.'},
  {w:'less than',p:'/les ðæn/',z:'少于',e:'The walk took less than an hour.'},
  {w:'the same as',p:'/ðə seɪm æz/',z:'和……相同',e:'My answer is the same as yours.'},
  {w:'as long as',p:'/æz lɔːŋ æz/',z:'只要；既然',e:'You can go as long as you finish.'},
  {w:'find out',p:'/faɪnd aʊt/',z:'查明；弄清',e:'Let us find out the answer.'},
  {w:'care about',p:'/ker əˈbaʊt/',z:'关心；在意',e:'Good friends care about each other.'},
  {w:'bring out',p:'/brɪŋ aʊt/',z:'使显现；出版',e:'The activity brings out her talent.'},
  {w:'reach for',p:'/riːtʃ fɔːr/',z:'伸手去拿',e:'He reached for the book.'},
  {w:'play a role',p:'/pleɪ ə roʊl/',z:'发挥作用；扮演角色',e:'Everyone can play a role in the team.'},
  {w:'come true',p:'/kʌm truː/',z:'实现；成真',e:'I hope your dream comes true.'},
  {w:'make promises',p:'/meɪk ˈprɑːmɪsɪz/',z:'许下诺言',e:'Do not make promises too quickly.'},
  {w:'take action',p:'/teɪk ˈækʃən/',z:'采取行动',e:'We should take action to help.'},
  {w:'be sure about',p:'/bi ʃʊr əˈbaʊt/',z:'确信；对……有把握',e:'Are you sure about the answer?'},
  {w:'have to do with',p:'/hæv tə duː wɪð/',z:'与……有关系',e:'The question has to do with health.'},
  {w:'in fact',p:'/ɪn fækt/',z:'事实上',e:'In fact, the task is quite easy.'},
  {w:'for example',p:'/fɔːr ɪɡˈzæmpəl/',z:'例如',e:'For example, you can read aloud.'},
  {w:'at first',p:'/æt fɜːrst/',z:'起初',e:'At first, the words seemed difficult.'},
  {w:'at last',p:'/æt læst/',z:'最后；终于',e:'At last, we reached the top.'},
  {w:'in the end',p:'/ɪn ði end/',z:'最后',e:'In the end, we chose the best plan.'},
  {w:'all kinds of',p:'/ɔːl kaɪndz əv/',z:'各种各样的',e:'The market sells all kinds of food.'},
  {w:'one day',p:'/wʌn deɪ/',z:'有一天',e:'One day, I want to visit London.'},
  {w:'another time',p:'/əˈnʌðər taɪm/',z:'另一次；再一次',e:'Let us try another time.'},
  {w:'of course not',p:'/əv kɔːrs nɑːt/',z:'当然不',e:'Of course not; you can stay.'},
  {w:'a few',p:'/ə fjuː/',z:'一些；几个',e:'I have a few questions.'},
  {w:'a little',p:'/ə ˈlɪtəl/',z:'一点；少量',e:'Add a little water.'},
  {w:'quite a few',p:'/kwaɪt ə fjuː/',z:'相当多',e:'Quite a few students joined.'},
  {w:'how often',p:'/haʊ ˈɔːfən/',z:'多久一次',e:'How often do you exercise?'},
  {w:'how long',p:'/haʊ lɔːŋ/',z:'多久；多长',e:'How long did you stay there?'},
  {w:'how many',p:'/haʊ ˈmeni/',z:'多少',e:'How many books did you read?'},
  {w:'how much',p:'/haʊ mʌtʃ/',z:'多少；多少钱',e:'How much water do you need?'},
  {w:'what kind of',p:'/wʌt kaɪnd əv/',z:'哪一种',e:'What kind of movie do you like?'},
  {w:'why not',p:'/waɪ nɑːt/',z:'为什么不',e:'Why not try a new hobby?'},
  {w:'what about',p:'/wʌt əˈbaʊt/',z:'……怎么样',e:'What about watching a cartoon?'},
  {w:'how about',p:'/haʊ əˈbaʊt/',z:'……怎么样',e:'How about taking a walk?'},
  {w:'would like',p:'/wʊd laɪk/',z:'想要',e:'I would like some tea.'},
  {w:'be ready for',p:'/bi ˈredi fɔːr/',z:'为……做好准备',e:'Be ready for the next lesson.'},
  {w:'be good at',p:'/bi ɡʊd æt/',z:'擅长',e:'She is good at drawing.'},
  {w:'be different from',p:'/bi ˈdɪfərənt frəm/',z:'与……不同',e:'This answer is different from mine.'},
  {w:'be similar to',p:'/bi ˈsɪmələr tuː/',z:'与……相似',e:'The two plans are similar to each other.'},
  {w:'be interested in',p:'/bi ˈɪntrəstɪd ɪn/',z:'对……感兴趣',e:'He is interested in science.'},
  {w:'be afraid of',p:'/bi əˈfreɪd əv/',z:'害怕……',e:'She is afraid of speaking loudly.'},
  {w:'be excited about',p:'/bi ɪkˈsaɪtɪd əˈbaʊt/',z:'对……感到兴奋',e:'We are excited about the trip.'},
  {w:'be famous for',p:'/bi ˈfeɪməs fɔːr/',z:'因……而出名',e:'The city is famous for its food.'},
  {w:'be full of',p:'/bi fʊl əv/',z:'充满',e:'The room is full of students.'},
  {w:'be able',p:'/bi ˈeɪbəl/',z:'能够',e:'You will be able to do it.'},
  {w:'make a plan',p:'/meɪk ə plæn/',z:'制订计划',e:'Let us make a plan for the week.'},
  {w:'make a decision',p:'/meɪk ə dɪˈsɪʒən/',z:'作出决定',e:'We need to make a decision.'},
  {w:'make a promise',p:'/meɪk ə ˈprɑːmɪs/',z:'作出承诺',e:'He made a promise to his parents.'},
  {w:'make a mistake',p:'/meɪk ə mɪˈsteɪk/',z:'犯错误',e:'Everyone can make a mistake.'},
  {w:'make friends',p:'/meɪk frendz/',z:'交朋友',e:'Sports help us make friends.'},
  {w:'make up',p:'/meɪk ʌp/',z:'编造；组成',e:'Can you make up a story?'},
  {w:'take care',p:'/teɪk ker/',z:'当心；保重',e:'Take care on the wet road.'},
  {w:'take care of',p:'/teɪk ker əv/',z:'照顾',e:'Please take care of the dog.'},
  {w:'take part in',p:'/teɪk pɑːrt ɪn/',z:'参加',e:'Many students take part in the activity.'},
  {w:'take a break',p:'/teɪk ə breɪk/',z:'休息一下',e:'Take a break after the lesson.'},
  {w:'get ready',p:'/ɡet ˈredi/',z:'准备好',e:'Get ready for school.'},
  {w:'get better',p:'/ɡet ˈbetər/',z:'变得更好',e:'Your English will get better.'},
  {w:'get up',p:'/ɡet ʌp/',z:'起床',e:'I get up at seven.'},
  {w:'get dressed',p:'/ɡet drest/',z:'穿衣服',e:'Get dressed before breakfast.'},
  {w:'go online',p:'/ɡoʊ ˌɑːnˈlaɪn/',z:'上网',e:'Do not go online too late.'},
  {w:'go camping',p:'/ɡoʊ ˈkæmpɪŋ/',z:'去露营',e:'We went camping near the lake.'},
  {w:'go shopping',p:'/ɡoʊ ˈʃɑːpɪŋ/',z:'去购物',e:'My mother goes shopping on Sundays.'},
  {w:'go fishing',p:'/ɡoʊ ˈfɪʃɪŋ/',z:'去钓鱼',e:'They went fishing last weekend.'},
  {w:'go skating',p:'/ɡoʊ ˈskeɪtɪŋ/',z:'去滑冰',e:'We go skating in winter.'},
  {w:'go hiking',p:'/ɡoʊ ˈhaɪkɪŋ/',z:'去远足',e:'They like to go hiking.'},
  {w:'go sightseeing',p:'/ɡoʊ ˈsaɪtsiːɪŋ/',z:'去观光',e:'We went sightseeing in the city.'},
  {w:'watch a movie',p:'/wɑːtʃ ə ˈmuːvi/',z:'看电影',e:'Let us watch a movie tonight.'},
  {w:'watch the news',p:'/wɑːtʃ ðə nuːz/',z:'看新闻',e:'My father watches the news.'},
  {w:'read books',p:'/riːd bʊks/',z:'读书',e:'I read books before bed.'},
  {w:'play the piano',p:'/pleɪ ðə piˈænoʊ/',z:'弹钢琴',e:'She can play the piano.'},
  {w:'play a sport',p:'/pleɪ ə spɔːrt/',z:'做运动',e:'Everyone should play a sport.'},
  {w:'learn a language',p:'/lɜːrn ə ˈlæŋɡwɪdʒ/',z:'学习语言',e:'I want to learn a language.'},
  {w:'learn from',p:'/lɜːrn frəm/',z:'向……学习',e:'We can learn from our mistakes.'},
  {w:'help with',p:'/help wɪð/',z:'帮助做……',e:'I help with the housework.'},
  {w:'spend time',p:'/spend taɪm/',z:'花时间',e:'Do not spend too much time online.'},
  {w:'spend time with',p:'/spend taɪm wɪð/',z:'和……一起度过时间',e:'I spend time with my family.'},
  {w:'use the Internet',p:'/juːz ði ˈɪntərnet/',z:'使用互联网',e:'Students use the Internet for research.'},
  {w:'read online',p:'/riːd ˌɑːnˈlaɪn/',z:'在线阅读',e:'I read online every evening.'},
  {w:'watch videos',p:'/wɑːtʃ ˈvɪdioʊz/',z:'看视频',e:'She watches videos for practice.'},
  {w:'ask questions',p:'/æsk ˈkwestʃənz/',z:'提问',e:'Do not be afraid to ask questions.'},
  {w:'answer clearly',p:'/ˈænsər ˈklɪrli/',z:'清楚地回答',e:'Answer clearly and slowly.'},
  {w:'speak English',p:'/spiːk ˈɪŋɡlɪʃ/',z:'说英语',e:'Try to speak English every day.'},
  {w:'write sentences',p:'/raɪt ˈsentənsɪz/',z:'写句子',e:'Write sentences with the new words.'},
  {w:'read aloud',p:'/riːd əˈlaʊd/',z:'大声朗读',e:'Read aloud in the morning.'},
  {w:'listen carefully',p:'/ˈlɪsən ˈkerfəli/',z:'仔细听',e:'Listen carefully to the teacher.'},
  {w:'practice speaking',p:'/ˈpræktɪs ˈspiːkɪŋ/',z:'练习口语',e:'Practice speaking with a partner.'},
  {w:'review words',p:'/rɪˈvjuː wɜːrdz/',z:'复习单词',e:'Review words before the test.'},
  {w:'remember words',p:'/rɪˈmembər wɜːrdz/',z:'记住单词',e:'Use the words in sentences to remember them.'},
  {w:'learn by heart',p:'/lɜːrn baɪ hɑːrt/',z:'背熟',e:'Learn the short poem by heart.'},
  {w:'understand',p:'/ˌʌndərˈstænd/',z:'v. 理解；懂得',e:'Try to understand the main idea.'},
  {w:'explain',p:'/ɪkˈspleɪn/',z:'v. 解释',e:'Can you explain the answer?'},
  {w:'describe',p:'/dɪˈskraɪb/',z:'v. 描述',e:'Describe the picture in English.'},
  {w:'discuss',p:'/dɪˈskʌs/',z:'v. 讨论',e:'Let us discuss the question.'},
  {w:'compare',p:'/kəmˈper/',z:'v. 比较',e:'Compare the two answers.'},
  {w:'correct',p:'/kəˈrekt/',z:'adj./v. 正确的；改正',e:'Please correct the mistake.'},
  {w:'mistake',p:'/mɪˈsteɪk/',z:'n. 错误',e:'Learn from every mistake.'},
  {w:'question',p:'/ˈkwestʃən/',z:'n. 问题',e:'Ask one question at a time.'},
  {w:'answer',p:'/ˈænsər/',z:'n./v. 答案；回答',e:'Write your answer here.'},
  {w:'meaning',p:'/ˈmiːnɪŋ/',z:'n. 意思',e:'What is the meaning of this word?'},
  {w:'sentence',p:'/ˈsentəns/',z:'n. 句子',e:'Make a sentence with the word.'},
  {w:'phrase',p:'/freɪz/',z:'n. 短语',e:'This phrase is useful in conversation.'},
  {w:'grammar',p:'/ˈɡræmər/',z:'n. 语法',e:'Grammar helps us write clearly.'},
  {w:'pronunciation',p:'/prəˌnʌnsiˈeɪʃən/',z:'n. 发音',e:'Your pronunciation is improving.'},
  {w:'vocabulary',p:'/vəˈkæbjəleri/',z:'n. 词汇',e:'Reading grows your vocabulary.'},
  {w:'textbook',p:'/ˈtekstbʊk/',z:'n. 课本',e:'Open your textbook to page ten.'},
  {w:'unit',p:'/ˈjuːnɪt/',z:'n. 单元',e:'We are learning Unit One.'},
  {w:'lesson',p:'/ˈlesən/',z:'n. 课；课时',e:'Today’s lesson is about hobbies.'},
  {w:'page',p:'/peɪdʒ/',z:'n. 页',e:'Please turn to page twelve.'},
  {w:'paragraph',p:'/ˈpærəɡræf/',z:'n. 段落',e:'Read the first paragraph.'},
  {w:'title',p:'/ˈtaɪtəl/',z:'n. 标题',e:'The title tells us the topic.'},
  {w:'topic',p:'/ˈtɑːpɪk/',z:'n. 话题；主题',e:'Today’s topic is healthy habits.'},
  {w:'idea',p:'/aɪˈdiːə/',z:'n. 想法；主意',e:'That is a good idea.'},
  {w:'main idea',p:'/meɪn aɪˈdiːə/',z:'n. 主旨',e:'Find the main idea first.'},
  {w:'detail',p:'/ˈdiːteɪl/',z:'n. 细节',e:'Look for details in the passage.'},
  {w:'passage',p:'/ˈpæsɪdʒ/',z:'n. 文章；段落',e:'Read the passage twice.'},
  {w:'conversation',p:'/ˌkɑːnvərˈseɪʃən/',z:'n. 对话',e:'Listen to the conversation.'},
  {w:'dialogue',p:'/ˈdaɪəlɔːɡ/',z:'n. 对话',e:'Practice the dialogue with a partner.'},
  {w:'speaker',p:'/ˈspiːkər/',z:'n. 说话者；发言人',e:'The speaker talks slowly.'},
  {w:'listener',p:'/ˈlɪsənər/',z:'n. 听者',e:'A good listener pays attention.'},
  {w:'partner',p:'/ˈpɑːrtnər/',z:'n. 搭档；伙伴',e:'Work with your partner.'},
  {w:'group',p:'/ɡruːp/',z:'n. 小组；群',e:'Discuss the answer in a group.'},
  {w:'classmate',p:'/ˈklæsmeɪt/',z:'n. 同班同学',e:'Ask a classmate for help.'},
  {w:'teacher',p:'/ˈtiːtʃər/',z:'n. 老师',e:'The teacher explained the rule.'},
  {w:'student',p:'/ˈstuːdənt/',z:'n. 学生',e:'Every student has a notebook.'},
  {w:'school',p:'/skuːl/',z:'n. 学校',e:'School starts at eight.'},
  {w:'class',p:'/klæs/',z:'n. 班级；课',e:'Our class is friendly.'},
  {w:'homework',p:'/ˈhoʊmwɜːrk/',z:'n. 家庭作业',e:'I finished my homework.'},
  {w:'test',p:'/test/',z:'n./v. 测验；测试',e:'We have a test on Friday.'},
  {w:'exam',p:'/ɪɡˈzæm/',z:'n. 考试',e:'The exam begins at nine.'},
  {w:'score',p:'/skɔːr/',z:'n. 分数',e:'She got a high score.'},
  {w:'grade',p:'/ɡreɪd/',z:'n. 成绩；年级',e:'He improved his grade.'},
  {w:'practice',p:'/ˈpræktɪs/',z:'v./n. 练习',e:'Practice makes progress.'},
  {w:'progress',p:'/ˈprɑːɡres/',z:'n. 进步',e:'You are making progress.'},
  {w:'success',p:'/səkˈses/',z:'n. 成功',e:'Hard work leads to success.'},
  {w:'challenge',p:'/ˈtʃælɪndʒ/',z:'n. 挑战',e:'This question is a challenge.'},
  {w:'goal',p:'/ɡoʊl/',z:'n. 目标',e:'Set a small goal for today.'},
  {w:'habit',p:'/ˈhæbɪt/',z:'n. 习惯',e:'Reading is a good habit.'},
  {w:'plan',p:'/plæn/',z:'n./v. 计划',e:'Make a plan before you begin.'},
  {w:'time',p:'/taɪm/',z:'n. 时间',e:'Use your time wisely.'},
  {w:'weekend',p:'/ˌwiːkˈend/',z:'n. 周末',e:'What do you do on weekends?'},
  {w:'weekday',p:'/ˈwiːkdeɪ/',z:'n. 工作日',e:'I get up early on weekdays.'},
  {w:'morning',p:'/ˈmɔːrnɪŋ/',z:'n. 早晨',e:'I read in the morning.'},
  {w:'afternoon',p:'/ˌæftərˈnuːn/',z:'n. 下午',e:'We have class in the afternoon.'},
  {w:'evening',p:'/ˈiːvnɪŋ/',z:'n. 晚上',e:'I review words in the evening.'},
  {w:'today',p:'/təˈdeɪ/',z:'adv. 今天',e:'Today is a good day to start.'},
  {w:'tomorrow',p:'/təˈmɑːroʊ/',z:'adv. 明天',e:'We will review tomorrow.'},
  {w:'yesterday',p:'/ˈjestərdeɪ/',z:'adv. 昨天',e:'I studied yesterday.'},
  {w:'early',p:'/ˈɜːrli/',z:'adv./adj. 早；早的',e:'She arrived early.'},
  {w:'late',p:'/leɪt/',z:'adv./adj. 迟；晚的',e:'Do not stay up late.'},
  {w:'always',p:'/ˈɔːlweɪz/',z:'adv. 总是',e:'I always read before bed.'},
  {w:'usually',p:'/ˈjuːʒuəli/',z:'adv. 通常',e:'We usually walk to school.'},
  {w:'sometimes',p:'/ˈsʌmtaɪmz/',z:'adv. 有时',e:'I sometimes watch a movie.'},
  {w:'never',p:'/ˈnevər/',z:'adv. 从不',e:'He never gives up.'},
  {w:'often',p:'/ˈɔːfən/',z:'adv. 经常',e:'How often do you practice?'},
  {w:'hard',p:'/hɑːrd/',z:'adv./adj. 努力地；困难的',e:'Study hard for the test.'},
  {w:'easy',p:'/ˈiːzi/',z:'adj. 容易的',e:'This exercise is easy.'},
  {w:'difficult',p:'/ˈdɪfɪkəlt/',z:'adj. 困难的',e:'The last question was difficult.'},
  {w:'important',p:'/ɪmˈpɔːrtənt/',z:'adj. 重要的',e:'Sleep is important for learning.'},
  {w:'useful',p:'/ˈjuːsfəl/',z:'adj. 有用的',e:'This phrase is useful.'},
  {w:'special',p:'/ˈspeʃəl/',z:'adj. 特别的',e:'Today is a special day.'},
  {w:'different',p:'/ˈdɪfərənt/',z:'adj. 不同的',e:'Everyone learns in a different way.'},
  {w:'same',p:'/seɪm/',z:'adj. 相同的',e:'We have the same goal.'},
  {w:'good',p:'/ɡʊd/',z:'adj. 好的',e:'That is a good plan.'},
  {w:'great',p:'/ɡreɪt/',z:'adj. 很好的',e:'You made great progress.'},
  {w:'best',p:'/best/',z:'adj. 最好的',e:'Do your best.'},
  {w:'bad',p:'/bæd/',z:'adj. 坏的；糟的',e:'It is bad to skip sleep.'},
  {w:'kind',p:'/kaɪnd/',z:'adj. 友好的；种类',e:'She is kind to everyone.'},
  {w:'friendly',p:'/ˈfrendli/',z:'adj. 友好的',e:'Our new classmate is friendly.'},
  {w:'funny',p:'/ˈfʌni/',z:'adj. 滑稽的',e:'The story is funny.'},
  {w:'serious',p:'/ˈsɪriəs/',z:'adj. 严肃的；严重的',e:'This is a serious question.'},
  {w:'beautiful',p:'/ˈbjuːtɪfəl/',z:'adj. 美丽的',e:'The view is beautiful.'},
  {w:'interesting',p:'/ˈɪntrəstɪŋ/',z:'adj. 有趣的',e:'The article is interesting.'},
  {w:'boring',p:'/ˈbɔːrɪŋ/',z:'adj. 无聊的',e:'The long wait was boring.'},
  {w:'exciting',p:'/ɪkˈsaɪtɪŋ/',z:'adj. 令人兴奋的',e:'The game was exciting.'},
  {w:'relaxing',p:'/rɪˈlæksɪŋ/',z:'adj. 令人放松的',e:'Music is relaxing.'},
  {w:'tired',p:'/ˈtaɪərd/',z:'adj. 疲倦的',e:'I felt tired after the hike.'},
  {w:'excited',p:'/ɪkˈsaɪtɪd/',z:'adj. 兴奋的',e:'We are excited about the trip.'},
  {w:'worried',p:'/ˈwɜːrid/',z:'adj. 担心的',e:'She felt worried before the exam.'},
  {w:'surprised',p:'/sərˈpraɪzd/',z:'adj. 惊讶的',e:'I was surprised by the result.'},
  {w:'afraid',p:'/əˈfreɪd/',z:'adj. 害怕的',e:'Do not be afraid of mistakes.'},
  {w:'ready',p:'/ˈredi/',z:'adj. 准备好的',e:'Are you ready to begin?'},
  {w:'busy',p:'/ˈbɪzi/',z:'adj. 忙碌的',e:'I am busy with my homework.'},
  {w:'free',p:'/friː/',z:'adj. 空闲的；免费的',e:'Are you free this afternoon?'},
  {w:'together',p:'/təˈɡeðər/',z:'adv. 一起',e:'Let us read together.'},
  {w:'alone',p:'/əˈloʊn/',z:'adv./adj. 独自；单独的',e:'She did not want to walk alone.'},
  {w:'outside',p:'/ˌaʊtˈsaɪd/',z:'adv./prep. 在外面',e:'The children played outside.'},
  {w:'inside',p:'/ˌɪnˈsaɪd/',z:'adv./prep. 在里面',e:'It is warm inside.'},
  {w:'nearby',p:'/ˌnɪrˈbaɪ/',z:'adv./adj. 附近',e:'There is a library nearby.'},
  {w:'far',p:'/fɑːr/',z:'adv./adj. 远的',e:'The station is not far.'},
  {w:'away',p:'/əˈweɪ/',z:'adv. 离开；远离',e:'The park is two miles away.'},
  {w:'around',p:'/əˈraʊnd/',z:'prep./adv. 在周围',e:'We walked around the lake.'},
  {w:'across',p:'/əˈkrɔːs/',z:'prep./adv. 穿过',e:'Walk across the bridge.'},
  {w:'along',p:'/əˈlɔːŋ/',z:'prep. 沿着',e:'We walked along the river.'},
  {w:'toward',p:'/təˈwɔːrd/',z:'prep. 朝；向',e:'He walked toward the door.'},
  {w:'without',p:'/wɪˈðaʊt/',z:'prep. 没有',e:'Do not leave without your bag.'},
  {w:'during',p:'/ˈdʊrɪŋ/',z:'prep. 在……期间',e:'No phones during the test.'},
  {w:'before',p:'/bɪˈfɔːr/',z:'prep./conj. 在……以前',e:'Read the question before answering.'},
  {w:'after',p:'/ˈæftər/',z:'prep./conj. 在……以后',e:'We went home after class.'},
  {w:'until',p:'/ənˈtɪl/',z:'prep./conj. 直到',e:'Wait until the rain stops.'},
  {w:'while',p:'/waɪl/',z:'conj. 当……时；而',e:'I listened while she read.'},
  {w:'then',p:'/ðen/',z:'adv. 然后；那么',e:'Read the word, then repeat it.'},
  {w:'also',p:'/ˈɔːlsoʊ/',z:'adv. 也；而且',e:'She also likes music.'},
  {w:'too',p:'/tuː/',z:'adv. 也；太',e:'I like the movie too.'},
  {w:'either',p:'/ˈiːðər/',z:'adv. 也；两者之一',e:'You can choose either answer.'},
  {w:'however',p:'/haʊˈevər/',z:'adv. 然而',e:'The task is hard; however, we can try.'},
  {w:'therefore',p:'/ˈðerfɔːr/',z:'adv. 因此',e:'It rained; therefore, we stayed home.'},
  {w:'because',p:'/bɪˈkɔːz/',z:'conj. 因为',e:'I stayed home because I was tired.'},
  {w:'if',p:'/ɪf/',z:'conj. 如果；是否',e:'Call me if you need help.'},
  {w:'when',p:'/wen/',z:'conj./adv. 当……时；何时',e:'Call me when you arrive.'},
  {w:'where',p:'/wer/',z:'adv./conj. 哪里；在那里',e:'Do you know where he lives?'},
  {w:'which',p:'/wɪtʃ/',z:'pron./adj. 哪一个',e:'Which book do you want?'},
  {w:'who',p:'/huː/',z:'pron. 谁',e:'Who is your partner?'},
  {w:'what',p:'/wʌt/',z:'pron./adj. 什么',e:'What do you want to learn?'},
  {w:'why',p:'/waɪ/',z:'adv. 为什么',e:'Why are you late?'},
  {w:'how',p:'/haʊ/',z:'adv. 怎样；如何',e:'How do you remember words?'},
  {w:'someone',p:'/ˈsʌmwʌn/',z:'pron. 某人',e:'Someone left a notebook here.'},
  {w:'somewhere',p:'/ˈsʌmwer/',z:'adv. 某处',e:'Let us meet somewhere quiet.'},
  {w:'nobody',p:'/ˈnoʊbədi/',z:'pron. 没有人',e:'Nobody knew the answer.'},
  {w:'everywhere',p:'/ˈevriwer/',z:'adv. 到处',e:'We looked everywhere for the key.'},
  {w:'anything',p:'/ˈeniθɪŋ/',z:'pron. 任何事物',e:'Do you need anything?'},
  {w:'everything',p:'/ˈevriθɪŋ/',z:'pron. 所有事物',e:'Everything is ready.'},
  {w:'nothing',p:'/ˈnʌθɪŋ/',z:'pron. 没有什么',e:'There is nothing to worry about.'},
  {w:'another',p:'/əˈnʌðər/',z:'adj./pron. 另一个',e:'Would you like another cup of tea?'},
  {w:'other',p:'/ˈʌðər/',z:'adj./pron. 其他的',e:'Some students chose other books.'},
  {w:'each',p:'/iːtʃ/',z:'pron./adj. 每个',e:'Each student has a turn.'},
  {w:'both',p:'/boʊθ/',z:'pron./adj. 两者都',e:'Both of them are right.'},
  {w:'all',p:'/ɔːl/',z:'pron./adj. 全部',e:'All the students joined.'},
  {w:'none',p:'/nʌn/',z:'pron. 没有一个',e:'None of the answers is correct.'},
  {w:'most',p:'/moʊst/',z:'pron./adj. 大多数',e:'Most of us like reading.'},
  {w:'few',p:'/fjuː/',z:'adj./pron. 少数',e:'Only a few were late.'},
  {w:'many',p:'/ˈmeni/',z:'adj./pron. 许多',e:'Many students enjoy sports.'},
  {w:'much',p:'/mʌtʃ/',z:'adj./pron. 许多',e:'We do not have much time.'},
  {w:'little',p:'/ˈlɪtəl/',z:'adj./pron. 少量',e:'There is little water left.'},
  {w:'enough',p:'/ɪˈnʌf/',z:'adj./adv. 足够',e:'That is enough for today.'},
  {w:'another one',p:'/əˈnʌðər wʌn/',z:'另一个',e:'This pen is broken; give me another one.'},
  {w:'a lot of',p:'/ə lɑːt əv/',z:'许多',e:'A lot of people joined the activity.'},
  {w:'lots of',p:'/lɑːts əv/',z:'许多',e:'There are lots of books here.'},
  {w:'kind of',p:'/kaɪnd əv/',z:'有点儿；一种',e:'It is kind of difficult.'},
  {w:'all kinds of',p:'/ɔːl kaɪndz əv/',z:'各种各样的',e:'The shop sells all kinds of snacks.'},
  {w:'a piece of',p:'/ə piːs əv/',z:'一片；一块',e:'I want a piece of bread.'},
  {w:'a pair of',p:'/ə per əv/',z:'一双；一对',e:'I bought a pair of shoes.'},
  {w:'a group of',p:'/ə ɡruːp əv/',z:'一组；一群',e:'A group of students visited the museum.'},
  {w:'a number of',p:'/ə ˈnʌmbər əv/',z:'许多',e:'A number of students volunteered.'},
  {w:'the number of',p:'/ðə ˈnʌmbər əv/',z:'……的数量',e:'The number of readers is growing.'},
  {w:'one of',p:'/wʌn əv/',z:'……之一',e:'She is one of my best friends.'},
  {w:'each other',p:'/iːtʃ ˈʌðər/',z:'互相；彼此',e:'We help each other.'},
  {w:'one another',p:'/wʌn əˈnʌðər/',z:'互相',e:'The players encouraged one another.'},
  {w:'by oneself',p:'/baɪ wʌnˈself/',z:'独自',e:'He finished the work by himself.'},
  {w:'on one’s own',p:'/ɑːn wʌnz oʊn/',z:'独立地',e:'She learned the song on her own.'},
  {w:'for oneself',p:'/fɔːr wʌnˈself/',z:'为自己',e:'Think for yourself.'},
  {w:'in person',p:'/ɪn ˈpɜːrsən/',z:'亲自',e:'The teacher spoke to us in person.'},
  {w:'in the future',p:'/ɪn ðə ˈfjuːtʃər/',z:'在将来',e:'What will you do in the future?'},
  {w:'in the past',p:'/ɪn ðə pæst/',z:'在过去',e:'People wrote letters in the past.'},
  {w:'from now on',p:'/frəm naʊ ɑːn/',z:'从现在开始',e:'From now on, I will review daily.'},
  {w:'right now',p:'/raɪt naʊ/',z:'现在；此刻',e:'I am busy right now.'},
  {w:'just now',p:'/dʒʌst naʊ/',z:'刚才',e:'He called just now.'},
  {w:'so far',p:'/soʊ fɑːr/',z:'到目前为止',e:'So far, everything is fine.'},
  {w:'once again',p:'/wʌns əˈɡen/',z:'再一次',e:'Please read it once again.'},
  {w:'again and again',p:'/əˈɡen ænd əˈɡen/',z:'一次又一次',e:'Practice it again and again.'},
  {w:'day by day',p:'/deɪ baɪ deɪ/',z:'一天天地',e:'Your English improves day by day.'},
  {w:'step by step',p:'/step baɪ step/',z:'一步一步地',e:'Learn the grammar step by step.'},
  {w:'little by little',p:'/ˈlɪtəl baɪ ˈlɪtəl/',z:'一点一点地',e:'Little by little, she gained confidence.'},
  {w:'side by side',p:'/saɪd baɪ saɪd/',z:'肩并肩地',e:'The friends walked side by side.'},
  {w:'face to face',p:'/feɪs tə feɪs/',z:'面对面地',e:'They had a face-to-face talk.'},
  {w:'in the middle of',p:'/ɪn ðə ˈmɪdəl əv/',z:'在……中间',e:'The library is in the middle of the town.'},
  {w:'at the top of',p:'/æt ðə tɑːp əv/',z:'在……顶部',e:'There is a flag at the top of the building.'},
  {w:'at the bottom of',p:'/æt ðə ˈbɑːtəm əv/',z:'在……底部',e:'The answer is at the bottom of the page.'},
  {w:'in front of',p:'/ɪn frʌnt əv/',z:'在……前面',e:'The bus stopped in front of the school.'},
  {w:'behind',p:'/bɪˈhaɪnd/',z:'prep./adv. 在后面',e:'The garden is behind the house.'},
  {w:'next to',p:'/nekst tuː/',z:'紧挨着',e:'Sit next to your partner.'},
  {w:'between',p:'/bɪˈtwiːn/',z:'在两者之间',e:'The shop is between the bank and the school.'},
  {w:'around the world',p:'/əˈraʊnd ðə wɜːrld/',z:'全世界',e:'People around the world enjoy music.'},
  {w:'in the countryside',p:'/ɪn ðə ˈkʌntrisaɪd/',z:'在乡下',e:'They spent the summer in the countryside.'},
  {w:'in the city',p:'/ɪn ðə ˈsɪti/',z:'在城市里',e:'There are many museums in the city.'},
  {w:'in the mountains',p:'/ɪn ðə ˈmaʊntənz/',z:'在山里',e:'We went hiking in the mountains.'},
  {w:'at the beach',p:'/æt ðə biːtʃ/',z:'在海滩',e:'They played volleyball at the beach.'},
  {w:'by the lake',p:'/baɪ ðə leɪk/',z:'在湖边',e:'We had lunch by the lake.'},
  {w:'on the farm',p:'/ɑːn ðə fɑːrm/',z:'在农场',e:'The children worked on the farm.'},
  {w:'at the market',p:'/æt ðə ˈmɑːrkɪt/',z:'在市场',e:'We bought fruit at the market.'},
  {w:'at the museum',p:'/æt ðə mjuˈziːəm/',z:'在博物馆',e:'We learned history at the museum.'},
  {w:'at the cinema',p:'/æt ðə ˈsɪnəmə/',z:'在电影院',e:'Let us meet at the cinema.'},
  {w:'on the Internet',p:'/ɑːn ði ˈɪntərnet/',z:'在互联网上',e:'Find more information on the Internet.'},
  {w:'on television',p:'/ɑːn ˈtelɪvɪʒən/',z:'在电视上',e:'The program is on television tonight.'},
  {w:'on the radio',p:'/ɑːn ðə ˈreɪdioʊ/',z:'在广播里',e:'I heard the news on the radio.'},
  {w:'by bus',p:'/baɪ bʌs/',z:'乘公共汽车',e:'We went there by bus.'},
  {w:'by bike',p:'/baɪ baɪk/',z:'骑自行车',e:'She goes to school by bike.'},
  {w:'on foot',p:'/ɑːn fʊt/',z:'步行',e:'I usually go to school on foot.'},
  {w:'by train',p:'/baɪ treɪn/',z:'乘火车',e:'They traveled by train.'},
  {w:'by plane',p:'/baɪ pleɪn/',z:'乘飞机',e:'We flew by plane.'},
  {w:'take the bus',p:'/teɪk ðə bʌs/',z:'乘公共汽车',e:'Take the bus to the station.'},
  {w:'ride a bike',p:'/raɪd ə baɪk/',z:'骑自行车',e:'I ride a bike every day.'},
  {w:'walk to school',p:'/wɔːk tə skuːl/',z:'步行上学',e:'Many students walk to school.'},
  {w:'arrive at',p:'/əˈraɪv æt/',z:'到达小地点',e:'We arrived at the station early.'},
  {w:'arrive in',p:'/əˈraɪv ɪn/',z:'到达大地点',e:'They arrived in Beijing at noon.'},
  {w:'leave for',p:'/liːv fɔːr/',z:'动身去',e:'We leave for school at seven.'},
  {w:'come back',p:'/kʌm bæk/',z:'回来',e:'Please come back before dinner.'},
  {w:'go back',p:'/ɡoʊ bæk/',z:'回去',e:'We will go back tomorrow.'},
  {w:'look for',p:'/lʊk fɔːr/',z:'寻找',e:'Look for the word in the text.'},
  {w:'look at',p:'/lʊk æt/',z:'看',e:'Look at the picture carefully.'},
  {w:'look like',p:'/lʊk laɪk/',z:'看起来像',e:'What does it look like?'},
  {w:'look after',p:'/lʊk ˈæftər/',z:'照顾',e:'Can you look after my cat?'},
  {w:'look forward to',p:'/lʊk ˈfɔːrwərd tuː/',z:'期待',e:'I look forward to the holiday.'},
  {w:'look up',p:'/lʊk ʌp/',z:'查阅；向上看',e:'Look up the word in a dictionary.'},
  {w:'look out',p:'/lʊk aʊt/',z:'小心',e:'Look out! The road is wet.'},
  {w:'look around',p:'/lʊk əˈraʊnd/',z:'环顾四周',e:'We looked around the museum.'},
  {w:'look different',p:'/lʊk ˈdɪfərənt/',z:'看起来不同',e:'You look different with short hair.'},
  {w:'look the same',p:'/lʊk ðə seɪm/',z:'看起来一样',e:'The twins look the same.'},
  {w:'sound like',p:'/saʊnd laɪk/',z:'听起来像',e:'That sounds like a good plan.'},
  {w:'feel better',p:'/fiːl ˈbetər/',z:'感觉好些',e:'I hope you feel better soon.'},
  {w:'feel well',p:'/fiːl wel/',z:'感觉健康',e:'Do you feel well today?'},
  {w:'taste good',p:'/teɪst ɡʊd/',z:'尝起来好吃',e:'The soup tastes good.'},
  {w:'smell good',p:'/smel ɡʊd/',z:'闻起来香',e:'The bread smells good.'},
  {w:'keep healthy',p:'/kiːp ˈhelθi/',z:'保持健康',e:'Exercise helps us keep healthy.'},
  {w:'stay healthy',p:'/steɪ ˈhelθi/',z:'保持健康',e:'Eat well to stay healthy.'},
  {w:'stay up',p:'/steɪ ʌp/',z:'熬夜',e:'Do not stay up too late.'},
  {w:'wake up',p:'/weɪk ʌp/',z:'醒来',e:'I wake up at six.'},
  {w:'fall asleep',p:'/fɔːl əˈsliːp/',z:'入睡',e:'I fall asleep quickly.'},
  {w:'feel tired',p:'/fiːl ˈtaɪərd/',z:'感觉疲倦',e:'I feel tired after school.'},
  {w:'feel nervous',p:'/fiːl ˈnɜːrvəs/',z:'感到紧张',e:'I feel nervous before a test.'},
  {w:'feel comfortable',p:'/fiːl ˈkʌmfərtəbəl/',z:'感觉舒服',e:'I feel comfortable in this chair.'},
  {w:'feel proud',p:'/fiːl praʊd/',z:'感到自豪',e:'Your parents feel proud of you.'},
  {w:'feel sorry',p:'/fiːl ˈsɑːri/',z:'感到抱歉',e:'I feel sorry about the mistake.'},
  {w:'become interested',p:'/bɪˈkʌm ˈɪntrəstɪd/',z:'变得感兴趣',e:'He became interested in science.'},
  {w:'become popular',p:'/bɪˈkʌm ˈpɑːpjələr/',z:'变得流行',e:'The game became popular.'},
  {w:'become better',p:'/bɪˈkʌm ˈbetər/',z:'变得更好',e:'The weather became better.'},
  {w:'become a habit',p:'/bɪˈkʌm ə ˈhæbɪt/',z:'成为习惯',e:'Reading can become a habit.'},
  {w:'try one’s best',p:'/traɪ wʌnz best/',z:'尽某人最大努力',e:'Try your best in the test.'},
  {w:'try again',p:'/traɪ əˈɡen/',z:'再试一次',e:'If you make a mistake, try again.'},
  {w:'try to do',p:'/traɪ tə duː/',z:'尽力做某事',e:'Try to speak clearly.'},
  {w:'want to be',p:'/wɑːnt tə biː/',z:'想成为',e:'What do you want to be?'},
  {w:'want to do',p:'/wɑːnt tə duː/',z:'想做某事',e:'I want to learn English.'},
  {w:'would like to',p:'/wʊd laɪk tuː/',z:'想要做',e:'I would like to join the club.'},
  {w:'hope to',p:'/hoʊp tuː/',z:'希望做',e:'I hope to travel someday.'},
  {w:'plan to',p:'/plæn tuː/',z:'计划做',e:'We plan to visit the museum.'},
  {w:'decide to',p:'/dɪˈsaɪd tuː/',z:'决定做',e:'She decided to study harder.'},
  {w:'promise to',p:'/ˈprɑːmɪs tuː/',z:'承诺做',e:'I promise to keep trying.'},
  {w:'learn to',p:'/lɜːrn tuː/',z:'学习做',e:'He learned to swim last summer.'},
  {w:'need to',p:'/niːd tuː/',z:'需要做',e:'You need to get ready.'},
  {w:'have to',p:'/hæv tuː/',z:'不得不；必须',e:'I have to finish my homework.'},
  {w:'be going to',p:'/bi ˈɡoʊɪŋ tuː/',z:'将要；打算',e:'We are going to watch a movie.'},
  {w:'be able to',p:'/bi ˈeɪbəl tuː/',z:'能够',e:'She is able to solve the problem.'},
  {w:'used to',p:'/juːst tuː/',z:'过去常常',e:'I used to play outside.'},
  {w:'keep doing',p:'/kiːp ˈduːɪŋ/',z:'继续做',e:'Keep doing your best.'},
  {w:'stop doing',p:'/stɑːp ˈduːɪŋ/',z:'停止做',e:'Stop talking and listen.'},
  {w:'finish doing',p:'/ˈfɪnɪʃ ˈduːɪŋ/',z:'做完某事',e:'Finish doing your homework first.'},
  {w:'enjoy doing',p:'/ɪnˈdʒɔɪ ˈduːɪŋ/',z:'喜欢做',e:'I enjoy reading books.'},
  {w:'mind doing',p:'/maɪnd ˈduːɪŋ/',z:'介意做',e:'Would you mind opening the door?'},
  {w:'practice doing',p:'/ˈpræktɪs ˈduːɪŋ/',z:'练习做',e:'Practice speaking every day.'},
  {w:'keep on',p:'/kiːp ɑːn/',z:'继续',e:'Keep on trying.'},
  {w:'work hard',p:'/wɜːrk hɑːrd/',z:'努力学习；努力工作',e:'Work hard and rest well.'},
  {w:'study hard',p:'/ˈstʌdi hɑːrd/',z:'努力学习',e:'Study hard for your goal.'},
  {w:'work out',p:'/wɜːrk aʊt/',z:'解决；锻炼',e:'Can you work out the answer?'},
  {w:'help out',p:'/help aʊt/',z:'帮助解决困难',e:'Can you help out at home?'},
  {w:'find out about',p:'/faɪnd aʊt əˈbaʊt/',z:'查明关于……',e:'Find out about the activity.'},
  {w:'think about',p:'/θɪŋk əˈbaʊt/',z:'考虑',e:'Think about your answer.'},
  {w:'think of',p:'/θɪŋk əv/',z:'想起；认为',e:'What do you think of the movie?'},
  {w:'talk about',p:'/tɔːk əˈbaʊt/',z:'谈论',e:'We talked about our hobbies.'},
  {w:'talk with',p:'/tɔːk wɪð/',z:'和……谈话',e:'I talked with my teacher.'},
  {w:'learn about',p:'/lɜːrn əˈbaʊt/',z:'了解',e:'We learned about healthy habits.'},
  {w:'hear about',p:'/hɪr əˈbaʊt/',z:'听说',e:'Did you hear about the competition?'},
  {w:'hear from',p:'/hɪr frəm/',z:'收到……来信',e:'I heard from my friend yesterday.'},
  {w:'hear of',p:'/hɪr əv/',z:'听说过',e:'Have you heard of this writer?'},
  {w:'agree with',p:'/əˈɡriː wɪð/',z:'同意……',e:'I agree with your idea.'},
  {w:'disagree with',p:'/ˌdɪsəˈɡriː wɪð/',z:'不同意……',e:'I disagree with that answer.'},
  {w:'share with',p:'/ʃer wɪð/',z:'与……分享',e:'Share the book with your partner.'},
  {w:'share ideas',p:'/ʃer aɪˈdiːəz/',z:'分享想法',e:'We share ideas in class.'},
  {w:'help each other',p:'/help iːtʃ ˈʌðər/',z:'互相帮助',e:'We help each other learn.'},
  {w:'work together',p:'/wɜːrk təˈɡeðər/',z:'一起工作',e:'Let us work together.'},
  {w:'study together',p:'/ˈstʌdi təˈɡeðər/',z:'一起学习',e:'We study together after school.'},
  {w:'play together',p:'/pleɪ təˈɡeðər/',z:'一起玩',e:'The children play together.'},
  {w:'learn together',p:'/lɜːrn təˈɡeðər/',z:'一起学习',e:'We learn together every day.'},
  {w:'make a list',p:'/meɪk ə lɪst/',z:'列清单',e:'Make a list of new words.'},
  {w:'make a difference',p:'/meɪk ə ˈdɪfərəns/',z:'有影响；起作用',e:'Small habits make a difference.'},
  {w:'make progress',p:'/meɪk ˈprɑːɡres/',z:'取得进步',e:'You can make progress every day.'},
  {w:'make friends with',p:'/meɪk frendz wɪð/',z:'与……交朋友',e:'She made friends with her new classmate.'},
  {w:'make money',p:'/meɪk ˈmʌni/',z:'赚钱',e:'Some people make money online.'},
  {w:'make time for',p:'/meɪk taɪm fɔːr/',z:'为……安排时间',e:'Make time for reading.'},
  {w:'take time',p:'/teɪk taɪm/',z:'花时间',e:'Good learning takes time.'},
  {w:'take notes',p:'/teɪk noʊts/',z:'记笔记',e:'Take notes in your lesson.'},
  {w:'take photos',p:'/teɪk ˈfoʊtoʊz/',z:'拍照',e:'We took photos at the beach.'},
  {w:'take a trip',p:'/teɪk ə trɪp/',z:'旅行',e:'We took a trip last summer.'},
  {w:'take a message',p:'/teɪk ə ˈmesɪdʒ/',z:'捎口信',e:'Can I take a message?'},
  {w:'give advice',p:'/ɡɪv ədˈvaɪs/',z:'提建议',e:'My teacher gave me good advice.'},
  {w:'give up',p:'/ɡɪv ʌp/',z:'放弃',e:'Never give up learning.'},
  {w:'give away',p:'/ɡɪv əˈweɪ/',z:'赠送；分发',e:'They gave away old books.'},
  {w:'give back',p:'/ɡɪv bæk/',z:'归还',e:'Please give back my pen.'},
  {w:'give a speech',p:'/ɡɪv ə spiːtʃ/',z:'发表演讲',e:'She gave a speech in class.'},
  {w:'get advice',p:'/ɡet ədˈvaɪs/',z:'得到建议',e:'Ask a teacher to get advice.'},
  {w:'get information',p:'/ɡet ˌɪnfərˈmeɪʃən/',z:'得到信息',e:'We got information from the website.'},
  {w:'get exercise',p:'/ɡet ˈeksərsaɪz/',z:'得到锻炼',e:'Walk to get exercise.'},
  {w:'get better at',p:'/ɡet ˈbetər æt/',z:'在……方面变得更好',e:'I want to get better at English.'},
  {w:'get worse',p:'/ɡet wɜːrs/',z:'变得更糟',e:'The weather may get worse.'},
  {w:'get lost',p:'/ɡet lɔːst/',z:'迷路',e:'We got lost in the city.'},
  {w:'get excited',p:'/ɡet ɪkˈsaɪtɪd/',z:'变得兴奋',e:'The children got excited.'},
  {w:'get nervous',p:'/ɡet ˈnɜːrvəs/',z:'变得紧张',e:'I get nervous before tests.'},
  {w:'get angry',p:'/ɡet ˈæŋɡri/',z:'变得生气',e:'Do not get angry about mistakes.'},
  {w:'get ready for',p:'/ɡet ˈredi fɔːr/',z:'为……做好准备',e:'Get ready for the next class.'},
  {w:'go out',p:'/ɡoʊ aʊt/',z:'出去',e:'We went out after dinner.'},
  {w:'go back to',p:'/ɡoʊ bæk tuː/',z:'回到',e:'I went back to my seat.'},
  {w:'go through',p:'/ɡoʊ θruː/',z:'经历；通过',e:'We went through a hard time.'},
  {w:'come true',p:'/kʌm truː/',z:'实现',e:'Her dream came true.'},
  {w:'come from',p:'/kʌm frəm/',z:'来自',e:'Where do you come from?'},
  {w:'come back',p:'/kʌm bæk/',z:'回来',e:'Come back before dark.'},
  {w:'run out of',p:'/rʌn aʊt əv/',z:'用光',e:'We ran out of water.'},
  {w:'run away',p:'/rʌn əˈweɪ/',z:'逃跑',e:'The dog ran away.'},
  {w:'run into',p:'/rʌn ˈɪntuː/',z:'偶然遇到；撞上',e:'I ran into an old friend.'},
  {w:'put on',p:'/pʊt ɑːn/',z:'穿上；上演',e:'Put on your coat.'},
  {w:'put off',p:'/pʊt ɔːf/',z:'推迟',e:'Do not put off your homework.'},
  {w:'put away',p:'/pʊt əˈweɪ/',z:'收起来',e:'Put away your books.'},
  {w:'put down',p:'/pʊt daʊn/',z:'放下；记下',e:'Put down the answer.'},
  {w:'turn on',p:'/tɜːrn ɑːn/',z:'打开',e:'Turn on the light.'},
  {w:'turn off',p:'/tɜːrn ɔːf/',z:'关闭',e:'Turn off your phone.'},
  {w:'turn up',p:'/tɜːrn ʌp/',z:'调高；出现',e:'Turn up the sound.'},
  {w:'turn down',p:'/tɜːrn daʊn/',z:'调低；拒绝',e:'Turn down the music.'},
  {w:'write about',p:'/raɪt əˈbaʊt/',z:'写关于……',e:'Write about your weekend.'},
  {w:'write to',p:'/raɪt tuː/',z:'写信给',e:'I write to my friend every week.'},
  {w:'read about',p:'/riːd əˈbaʊt/',z:'读到关于……',e:'I read about the city online.'},
  {w:'talk to',p:'/tɔːk tuː/',z:'和……交谈',e:'Talk to your teacher.'},
  {w:'listen to',p:'/ˈlɪsən tuː/',z:'听',e:'Listen to the sentence.'},
  {w:'look at',p:'/lʊk æt/',z:'看',e:'Look at the example.'},
  {w:'look like',p:'/lʊk laɪk/',z:'看起来像',e:'It looks like a good idea.'},
  {w:'look for',p:'/lʊk fɔːr/',z:'寻找',e:'Look for the answer in the passage.'},
  {w:'look after',p:'/lʊk ˈæftər/',z:'照顾',e:'Look after yourself.'},
  {w:'look through',p:'/lʊk θruː/',z:'浏览；翻阅',e:'Look through the textbook.'},
  {w:'look up to',p:'/lʊk ʌp tuː/',z:'钦佩',e:'Many students look up to the teacher.'},
  {w:'find a way',p:'/faɪnd ə weɪ/',z:'找到办法',e:'We can find a way to solve it.'},
  {w:'find a job',p:'/faɪnd ə dʒɑːb/',z:'找到工作',e:'He hopes to find a job soon.'},
  {w:'find time',p:'/faɪnd taɪm/',z:'找到时间',e:'Find time to read every day.'},
  {w:'find someone',p:'/faɪnd ˈsʌmwʌn/',z:'找到某人',e:'Find someone to practice with.'},
  {w:'keep in touch',p:'/kiːp ɪn tʌtʃ/',z:'保持联系',e:'Let us keep in touch.'},
  {w:'keep quiet',p:'/kiːp ˈkwaɪət/',z:'保持安静',e:'Please keep quiet in the library.'},
  {w:'keep healthy',p:'/kiːp ˈhelθi/',z:'保持健康',e:'Eat well to keep healthy.'},
  {w:'keep trying',p:'/kiːp ˈtraɪɪŋ/',z:'继续尝试',e:'Keep trying and you will improve.'},
  {w:'keep learning',p:'/kiːp ˈlɜːrnɪŋ/',z:'继续学习',e:'Keep learning every day.'},
  {w:'stay healthy',p:'/steɪ ˈhelθi/',z:'保持健康',e:'Exercise to stay healthy.'},
  {w:'stay with',p:'/steɪ wɪð/',z:'和……待在一起',e:'I stayed with my grandparents.'},
  {w:'stay at',p:'/steɪ æt/',z:'暂住在',e:'We stayed at a small hotel.'},
  {w:'live in',p:'/lɪv ɪn/',z:'居住在',e:'She lives in Luoyang.'},
  {w:'live with',p:'/lɪv wɪð/',z:'和……一起居住',e:'He lives with his parents.'},
  {w:'work as',p:'/wɜːrk æz/',z:'以……身份工作',e:'She works as a doctor.'},
  {w:'work on',p:'/wɜːrk ɑːn/',z:'从事；致力于',e:'We are working on a project.'},
  {w:'work out',p:'/wɜːrk aʊt/',z:'算出；解决',e:'Can you work out the problem?'},
  {w:'work hard at',p:'/wɜːrk hɑːrd æt/',z:'努力学习或工作',e:'Work hard at your English.'},
  {w:'study for',p:'/ˈstʌdi fɔːr/',z:'为……学习',e:'I study for the exam.'},
  {w:'study abroad',p:'/ˈstʌdi əˈbrɔːd/',z:'出国留学',e:'She hopes to study abroad.'},
  {w:'study online',p:'/ˈstʌdi ˌɑːnˈlaɪn/',z:'在线学习',e:'Many students study online.'},
  {w:'learn English',p:'/lɜːrn ˈɪŋɡlɪʃ/',z:'学英语',e:'I learn English every day.'},
  {w:'learn from mistakes',p:'/lɜːrn frəm mɪˈsteɪks/',z:'从错误中学习',e:'Learn from mistakes and try again.'},
  {w:'practice every day',p:'/ˈpræktɪs ˈevri deɪ/',z:'每天练习',e:'Practice every day for progress.'},
  {w:'review every week',p:'/rɪˈvjuː ˈevri wiːk/',z:'每周复习',e:'Review every week to remember more.'},
  {w:'reach a goal',p:'/riːtʃ ə ɡoʊl/',z:'达到目标',e:'You can reach a goal step by step.'},
  {w:'achieve a dream',p:'/əˈtʃiːv ə driːm/',z:'实现梦想',e:'Hard work helps achieve a dream.'},
  {w:'follow a plan',p:'/ˈfɑːloʊ ə plæn/',z:'按计划进行',e:'Follow a plan for the week.'},
  {w:'change a habit',p:'/tʃeɪndʒ ə ˈhæbɪt/',z:'改变习惯',e:'It takes time to change a habit.'},
  {w:'build a habit',p:'/bɪld ə ˈhæbɪt/',z:'养成习惯',e:'Build a habit with small steps.'},
  {w:'break a habit',p:'/breɪk ə ˈhæbɪt/',z:'改掉习惯',e:'It is hard to break a habit.'},
  {w:'develop a hobby',p:'/dɪˈveləp ə ˈhɑːbi/',z:'培养爱好',e:'Develop a hobby you enjoy.'},
  {w:'choose a hobby',p:'/tʃuːz ə ˈhɑːbi/',z:'选择爱好',e:'Choose a hobby for the new term.'},
  {w:'join a club',p:'/dʒɔɪn ə klʌb/',z:'参加俱乐部',e:'She wants to join a music club.'},
  {w:'join a competition',p:'/dʒɔɪn ə ˌkɑːmpəˈtɪʃən/',z:'参加比赛',e:'He joined a writing competition.'},
  {w:'win a prize',p:'/wɪn ə praɪz/',z:'赢得奖品',e:'She won a prize for her story.'},
  {w:'get a chance',p:'/ɡet ə tʃæns/',z:'得到机会',e:'Everyone gets a chance to speak.'},
  {w:'have a chance',p:'/hæv ə tʃæns/',z:'有机会',e:'I hope to have a chance to travel.'},
  {w:'give a chance',p:'/ɡɪv ə tʃæns/',z:'给机会',e:'Give yourself a chance.'},
  {w:'make a choice',p:'/meɪk ə tʃɔɪs/',z:'作出选择',e:'Make a choice after thinking.'},
  {w:'make a change',p:'/meɪk ə tʃeɪndʒ/',z:'作出改变',e:'One small change can help.'},
  {w:'make a mistake',p:'/meɪk ə mɪˈsteɪk/',z:'犯错误',e:'It is okay to make a mistake.'},
  {w:'ask for help',p:'/æsk fɔːr help/',z:'寻求帮助',e:'Ask for help when you need it.'},
  {w:'ask for advice',p:'/æsk fɔːr ədˈvaɪs/',z:'征求建议',e:'Ask for advice from your teacher.'},
  {w:'listen for',p:'/ˈlɪsən fɔːr/',z:'留心听',e:'Listen for the key word.'},
  {w:'speak up',p:'/spiːk ʌp/',z:'大声说；发言',e:'Please speak up in class.'},
  {w:'write clearly',p:'/raɪt ˈklɪrli/',z:'清楚地写',e:'Write clearly in your notebook.'},
  {w:'read carefully',p:'/riːd ˈkerfəli/',z:'仔细阅读',e:'Read carefully before answering.'},
  {w:'answer the question',p:'/ˈænsər ðə ˈkwestʃən/',z:'回答问题',e:'Answer the question in English.'},
  {w:'check the answer',p:'/tʃek ði ˈænsər/',z:'检查答案',e:'Check the answer after trying.'},
  {w:'check the spelling',p:'/tʃek ðə ˈspelɪŋ/',z:'检查拼写',e:'Check the spelling twice.'},
  {w:'check the meaning',p:'/tʃek ðə ˈmiːnɪŋ/',z:'检查含义',e:'Check the meaning in the dictionary.'},
  {w:'use a dictionary',p:'/juːz ə ˈdɪkʃəneri/',z:'使用词典',e:'Use a dictionary for new words.'},
  {w:'use an example',p:'/juːz ən ɪɡˈzæmpəl/',z:'使用例子',e:'Use an example to explain.'},
  {w:'use a sentence',p:'/juːz ə ˈsentəns/',z:'使用句子',e:'Use a sentence to remember it.'},
  {w:'copy the sentence',p:'/ˈkɑːpi ðə ˈsentəns/',z:'抄写句子',e:'Copy the sentence in your notebook.'},
  {w:'read the textbook',p:'/riːd ðə ˈtekstbʊk/',z:'读课本',e:'Read the textbook before class.'},
  {w:'open the book',p:'/ˈoʊpən ðə bʊk/',z:'打开书',e:'Open the book to Unit One.'},
  {w:'close the book',p:'/kloʊz ðə bʊk/',z:'合上书',e:'Close the book and recall the words.'},
  {w:'turn the page',p:'/tɜːrn ðə peɪdʒ/',z:'翻页',e:'Turn the page slowly.'},
  {w:'read the title',p:'/riːd ðə ˈtaɪtəl/',z:'读标题',e:'Read the title first.'},
  {w:'find the answer',p:'/faɪnd ði ˈænsər/',z:'找到答案',e:'Find the answer in the passage.'},
  {w:'underline the word',p:'/ˌʌndərˈlaɪn ðə wɜːrd/',z:'给单词画线',e:'Underline the important word.'},
  {w:'circle the answer',p:'/ˈsɜːrkəl ði ˈænsər/',z:'圈出答案',e:'Circle the best answer.'},
  {w:'fill in',p:'/fɪl ɪn/',z:'填写',e:'Fill in the missing word.'},
  {w:'match the words',p:'/mætʃ ðə wɜːrdz/',z:'匹配单词',e:'Match the words with meanings.'},
  {w:'complete the sentence',p:'/kəmˈpliːt ðə ˈsentəns/',z:'完成句子',e:'Complete the sentence with one word.'},
  {w:'repeat the sentence',p:'/rɪˈpiːt ðə ˈsentəns/',z:'重复句子',e:'Repeat the sentence after the audio.'},
  {w:'read in pairs',p:'/riːd ɪn perz/',z:'两人一组朗读',e:'Read the dialogue in pairs.'},
  {w:'work in groups',p:'/wɜːrk ɪn ɡruːps/',z:'分组活动',e:'Work in groups of four.'},
  {w:'share the answer',p:'/ʃer ði ˈænsər/',z:'分享答案',e:'Share the answer with the class.'},
  {w:'check together',p:'/tʃek təˈɡeðər/',z:'一起检查',e:'Let us check together.'},
  {w:'learn by doing',p:'/lɜːrn baɪ ˈduːɪŋ/',z:'在做中学',e:'We learn by doing.'},
  {w:'learn by reading',p:'/lɜːrn baɪ ˈriːdɪŋ/',z:'通过阅读学习',e:'We learn by reading.'},
  {w:'learn by listening',p:'/lɜːrn baɪ ˈlɪsənɪŋ/',z:'通过听学习',e:'We learn by listening.'},
  {w:'learn by speaking',p:'/lɜːrn baɪ ˈspiːkɪŋ/',z:'通过说学习',e:'We learn by speaking.'},
  {w:'learn from books',p:'/lɜːrn frəm bʊks/',z:'从书中学习',e:'We learn from books.'},
  {w:'learn from life',p:'/lɜːrn frəm laɪf/',z:'从生活中学习',e:'We learn from life.'},
  {w:'learn something new',p:'/lɜːrn ˈsʌmθɪŋ nuː/',z:'学习新东西',e:'Learn something new today.'},
  {w:'know about',p:'/noʊ əˈbaʊt/',z:'了解',e:'I know about the activity.'},
  {w:'know how to',p:'/noʊ haʊ tuː/',z:'知道如何',e:'Do you know how to use it?'},
  {w:'understand the text',p:'/ˌʌndərˈstænd ðə tekst/',z:'理解文章',e:'Try to understand the text.'},
  {w:'understand the question',p:'/ˌʌndərˈstænd ðə ˈkwestʃən/',z:'理解问题',e:'First understand the question.'},
  {w:'remember the rule',p:'/rɪˈmembər ðə ruːl/',z:'记住规则',e:'Remember the rule before writing.'},
  {w:'follow the rule',p:'/ˈfɑːloʊ ðə ruːl/',z:'遵守规则',e:'Follow the rule in the exercise.'},
  {w:'break the rule',p:'/breɪk ðə ruːl/',z:'违反规则',e:'Do not break the rule.'},
  {w:'follow instructions',p:'/ˈfɑːloʊ ɪnˈstrʌkʃənz/',z:'遵循说明',e:'Follow the instructions carefully.'},
  {w:'give instructions',p:'/ɡɪv ɪnˈstrʌkʃənz/',z:'给出说明',e:'The teacher gave instructions.'},
  {w:'pay attention',p:'/peɪ əˈtenʃən/',z:'注意；专心',e:'Pay attention to the pronunciation.'},
  {w:'pay attention to',p:'/peɪ əˈtenʃən tuː/',z:'注意……',e:'Pay attention to the ending.'},
  {w:'take responsibility',p:'/teɪk rɪˌspɑːnsəˈbɪləti/',z:'承担责任',e:'Take responsibility for your work.'},
  {w:'be responsible for',p:'/bi rɪˈspɑːnsəbəl fɔːr/',z:'对……负责',e:'You are responsible for the books.'},
  {w:'be proud of',p:'/bi praʊd əv/',z:'为……骄傲',e:'We are proud of our progress.'},
  {w:'be good for',p:'/bi ɡʊd fɔːr/',z:'对……有好处',e:'Exercise is good for your health.'},
  {w:'be bad for',p:'/bi bæd fɔːr/',z:'对……有坏处',e:'Too much sugar is bad for teeth.'},
  {w:'be ready to',p:'/bi ˈredi tuː/',z:'准备做',e:'I am ready to answer.'},
  {w:'be afraid to',p:'/bi əˈfreɪd tuː/',z:'害怕做',e:'Do not be afraid to ask.'},
  {w:'be happy to',p:'/bi ˈhæpi tuː/',z:'高兴做',e:'I am happy to help.'},
  {w:'be sorry to',p:'/bi ˈsɑːri tuː/',z:'遗憾做',e:'I am sorry to hear that.'},
  {w:'be surprised to',p:'/bi sərˈpraɪzd tuː/',z:'惊讶于',e:'We were surprised to see him.'},
  {w:'be excited to',p:'/bi ɪkˈsaɪtɪd tuː/',z:'兴奋地做',e:'I am excited to start.'},
  {w:'be interested to',p:'/bi ˈɪntrəstɪd tuː/',z:'对做……感兴趣',e:'I am interested to learn more.'},
  {w:'be afraid that',p:'/bi əˈfreɪd ðæt/',z:'担心……',e:'I am afraid that we are late.'},
  {w:'be sure that',p:'/bi ʃʊr ðæt/',z:'确信……',e:'I am sure that you can do it.'},
  {w:'be glad that',p:'/bi ɡlæd ðæt/',z:'高兴……',e:'I am glad that you came.'},
  {w:'be sorry that',p:'/bi ˈsɑːri ðæt/',z:'遗憾……',e:'I am sorry that I was late.'},
  {w:'be different',p:'/bi ˈdɪfərənt/',z:'不同',e:'It is okay to be different.'},
  {w:'be similar',p:'/bi ˈsɪmələr/',z:'相似',e:'The two ideas are similar.'},
  {w:'be careful',p:'/bi ˈkerfəl/',z:'小心',e:'Be careful on the wet floor.'},
  {w:'be quiet',p:'/bi ˈkwaɪət/',z:'保持安静',e:'Please be quiet in class.'},
  {w:'be active',p:'/bi ˈæktɪv/',z:'积极；活跃',e:'Be active in the discussion.'},
  {w:'be creative',p:'/bi kriˈeɪtɪv/',z:'有创造力',e:'Be creative with your project.'},
  {w:'be patient',p:'/bi ˈpeɪʃənt/',z:'耐心',e:'Be patient with yourself.'},
  {w:'be kind',p:'/bi kaɪnd/',z:'友善',e:'Be kind to your classmates.'},
  {w:'be honest',p:'/bi ˈɑːnɪst/',z:'诚实',e:'Be honest about the mistake.'},
  {w:'be helpful',p:'/bi ˈhelpfəl/',z:'有帮助的',e:'Your advice was helpful.'},
  {w:'be useful',p:'/bi ˈjuːsfəl/',z:'有用的',e:'This note will be useful.'},
  {w:'be important',p:'/bi ɪmˈpɔːrtənt/',z:'重要的',e:'It is important to sleep well.'},
  {w:'be possible',p:'/bi ˈpɑːsəbəl/',z:'可能的',e:'It is possible to improve.'},
  {w:'be impossible',p:'/bi ɪmˈpɑːsəbəl/',z:'不可能的',e:'Nothing is impossible with practice.'},
  {w:'be ready for',p:'/bi ˈredi fɔːr/',z:'准备好面对',e:'Be ready for a new challenge.'},
  {w:'be good at',p:'/bi ɡʊd æt/',z:'擅长',e:'She is good at telling stories.'},
  {w:'be bad at',p:'/bi bæd æt/',z:'不擅长',e:'I am bad at remembering names.'},
  {w:'be different from',p:'/bi ˈdɪfərənt frəm/',z:'与……不同',e:'This unit is different from the last one.'},
  {w:'be similar to',p:'/bi ˈsɪmələr tuː/',z:'与……相似',e:'This word is similar to that one.'},
  {w:'be famous as',p:'/bi ˈfeɪməs æz/',z:'作为……出名',e:'He is famous as a writer.'},
  {w:'be famous for',p:'/bi ˈfeɪməs fɔːr/',z:'因……著名',e:'The town is famous for its food.'},
  {w:'be full of',p:'/bi fʊl əv/',z:'充满',e:'The book is full of useful examples.'},
  {w:'be made of',p:'/bi meɪd əv/',z:'由……制成',e:'The chair is made of wood.'},
  {w:'be made from',p:'/bi meɪd frəm/',z:'由……制成',e:'Paper is made from wood.'},
  {w:'be born',p:'/bi bɔːrn/',z:'出生',e:'She was born in Luoyang.'},
  {w:'become famous',p:'/bɪˈkʌm ˈfeɪməs/',z:'变得有名',e:'The young writer became famous.'},
  {w:'become rich',p:'/bɪˈkʌm rɪtʃ/',z:'变得富有',e:'He did not become rich quickly.'},
  {w:'become successful',p:'/bɪˈkʌm səkˈsesfəl/',z:'获得成功',e:'She became successful through hard work.'},
  {w:'become a teacher',p:'/bɪˈkʌm ə ˈtiːtʃər/',z:'成为老师',e:'He wants to become a teacher.'},
  {w:'become a scientist',p:'/bɪˈkʌm ə ˈsaɪəntɪst/',z:'成为科学家',e:'She hopes to become a scientist.'},
  {w:'become a doctor',p:'/bɪˈkʌm ə ˈdɑːktər/',z:'成为医生',e:'He plans to become a doctor.'},
  {w:'become a writer',p:'/bɪˈkʌm ə ˈraɪtər/',z:'成为作家',e:'She dreams of becoming a writer.'},
  {w:'become a pilot',p:'/bɪˈkʌm ə ˈpaɪlət/',z:'成为飞行员',e:'He wants to become a pilot.'},
  {w:'grow into',p:'/ɡroʊ ˈɪntuː/',z:'成长为；发展成',e:'The small idea grew into a project.'},
  {w:'grow older',p:'/ɡroʊ ˈoʊldər/',z:'长大；变老',e:'We learn new things as we grow older.'},
  {w:'grow stronger',p:'/ɡroʊ ˈstrɔːŋɡər/',z:'变得更强',e:'Practice helps your memory grow stronger.'},
  {w:'grow vegetables',p:'/ɡroʊ ˈvedʒtəbəlz/',z:'种蔬菜',e:'They grow vegetables on the farm.'},
  {w:'grow flowers',p:'/ɡroʊ ˈflaʊərz/',z:'种花',e:'My grandmother grows flowers.'},
  {w:'grow quickly',p:'/ɡroʊ ˈkwɪkli/',z:'成长迅速',e:'The plants grow quickly in spring.'},
  {w:'grow slowly',p:'/ɡroʊ ˈsloʊli/',z:'慢慢成长',e:'Good habits grow slowly.'},
  {w:'future job',p:'/ˈfjuːtʃər dʒɑːb/',z:'未来职业',e:'Think about your future job.'},
  {w:'dream job',p:'/driːm dʒɑːb/',z:'理想职业',e:'A dream job should fit your interests.'},
  {w:'school life',p:'/skuːl laɪf/',z:'学校生活',e:'School life can be busy and fun.'},
  {w:'daily life',p:'/ˈdeɪli laɪf/',z:'日常生活',e:'English is useful in daily life.'},
  {w:'family life',p:'/ˈfæməli laɪf/',z:'家庭生活',e:'Family life teaches us to care.'},
  {w:'healthy life',p:'/ˈhelθi laɪf/',z:'健康生活',e:'Exercise supports a healthy life.'},
  {w:'successful life',p:'/səkˈsesfəl laɪf/',z:'成功人生',e:'A successful life needs balance.'},
  {w:'happy life',p:'/ˈhæpi laɪf/',z:'幸福生活',e:'Kindness can bring a happy life.'},
  {w:'future plan',p:'/ˈfjuːtʃər plæn/',z:'未来计划',e:'Write down your future plan.'},
  {w:'study plan',p:'/ˈstʌdi plæn/',z:'学习计划',e:'Make a study plan for the term.'},
  {w:'work plan',p:'/wɜːrk plæn/',z:'工作计划',e:'The team made a work plan.'},
  {w:'weekly plan',p:'/ˈwiːkli plæn/',z:'每周计划',e:'Our weekly plan includes review.'},
  {w:'daily plan',p:'/ˈdeɪli plæn/',z:'每日计划',e:'The daily plan has three steps.'},
  {w:'new term',p:'/nuː tɜːrm/',z:'新学期',e:'The new term starts next week.'},
  {w:'first term',p:'/fɜːrst tɜːrm/',z:'上学期；第一学期',e:'This list is for the first term.'},
  {w:'second term',p:'/ˈsekənd tɜːrm/',z:'下学期；第二学期',e:'We will review it in the second term.'},
  {w:'new subject',p:'/nuː ˈsʌbdʒekt/',z:'新科目',e:'Science is a new subject for some students.'},
  {w:'school subject',p:'/skuːl ˈsʌbdʒekt/',z:'学校科目',e:'English is my favorite school subject.'},
  {w:'English class',p:'/ˈɪŋɡlɪʃ klæs/',z:'英语课',e:'We speak English in English class.'},
  {w:'English book',p:'/ˈɪŋɡlɪʃ bʊk/',z:'英语课本',e:'Bring your English book tomorrow.'},
  {w:'English lesson',p:'/ˈɪŋɡlɪʃ ˈlesən/',z:'英语课时',e:'The English lesson starts at eight.'},
  {w:'English word',p:'/ˈɪŋɡlɪʃ wɜːrd/',z:'英语单词',e:'Learn one English word today.'},
  {w:'English sentence',p:'/ˈɪŋɡlɪʃ ˈsentəns/',z:'英语句子',e:'Write an English sentence.'},
  {w:'English story',p:'/ˈɪŋɡlɪʃ ˈstɔːri/',z:'英语故事',e:'The English story is interesting.'},
  {w:'English song',p:'/ˈɪŋɡlɪʃ sɔːŋ/',z:'英文歌曲',e:'We learned an English song.'},
  {w:'English movie',p:'/ˈɪŋɡlɪʃ ˈmuːvi/',z:'英语电影',e:'An English movie can be good practice.'},
  {w:'English speaker',p:'/ˈɪŋɡlɪʃ ˈspiːkər/',z:'英语说话者',e:'The English speaker talked slowly.'},
  {w:'English practice',p:'/ˈɪŋɡlɪʃ ˈpræktɪs/',z:'英语练习',e:'Daily English practice is useful.'},
  {w:'English test',p:'/ˈɪŋɡlɪʃ test/',z:'英语测试',e:'The English test is on Friday.'},
  {w:'English grade',p:'/ˈɪŋɡlɪʃ ɡreɪd/',z:'英语成绩',e:'Her English grade improved.'},
  {w:'English goal',p:'/ˈɪŋɡlɪʃ ɡoʊl/',z:'英语目标',e:'My English goal is to speak clearly.'},
  {w:'English habit',p:'/ˈɪŋɡlɪʃ ˈhæbɪt/',z:'英语学习习惯',e:'Reading is a useful English habit.'},
  {w:'English notebook',p:'/ˈɪŋɡlɪʃ ˈnoʊtbʊk/',z:'英语笔记本',e:'Write the new words in your English notebook.'},
  {w:'English dictionary',p:'/ˈɪŋɡlɪʃ ˈdɪkʃəneri/',z:'英语词典',e:'Use an English dictionary when needed.'},
  {w:'English corner',p:'/ˈɪŋɡlɪʃ ˈkɔːrnər/',z:'英语角',e:'She joined the English corner.'},
  {w:'English club',p:'/ˈɪŋɡlɪʃ klʌb/',z:'英语俱乐部',e:'The English club meets on Friday.'},
  {w:'English speech',p:'/ˈɪŋɡlɪʃ spiːtʃ/',z:'英语演讲',e:'He prepared an English speech.'},
  {w:'English competition',p:'/ˈɪŋɡlɪʃ ˌkɑːmpəˈtɪʃən/',z:'英语比赛',e:'She joined an English competition.'},
  {w:'English reading',p:'/ˈɪŋɡlɪʃ ˈriːdɪŋ/',z:'英语阅读',e:'English reading improves vocabulary.'},
  {w:'English listening',p:'/ˈɪŋɡlɪʃ ˈlɪsənɪŋ/',z:'英语听力',e:'English listening takes daily practice.'},
  {w:'English speaking',p:'/ˈɪŋɡlɪʃ ˈspiːkɪŋ/',z:'英语口语',e:'English speaking becomes easier with practice.'},
  {w:'English writing',p:'/ˈɪŋɡlɪʃ ˈraɪtɪŋ/',z:'英语写作',e:'English writing needs clear sentences.'},
  {w:'English grammar',p:'/ˈɪŋɡlɪʃ ˈɡræmər/',z:'英语语法',e:'English grammar helps us write.'},
  {w:'English pronunciation',p:'/ˈɪŋɡlɪʃ prəˌnʌnsiˈeɪʃən/',z:'英语发音',e:'English pronunciation improves by listening.'},
  {w:'English vocabulary',p:'/ˈɪŋɡlɪʃ vəˈkæbjəleri/',z:'英语词汇',e:'English vocabulary grows every day.'},
  {w:'English phrase',p:'/ˈɪŋɡlɪʃ freɪz/',z:'英语短语',e:'Learn an English phrase in context.'},
  {w:'English meaning',p:'/ˈɪŋɡlɪʃ ˈmiːnɪŋ/',z:'英语含义',e:'Check the English meaning first.'},
  {w:'English example',p:'/ˈɪŋɡlɪʃ ɪɡˈzæmpəl/',z:'英语例子',e:'The English example is clear.'},
  {w:'English context',p:'/ˈɪŋɡlɪʃ ˈkɑːntekst/',z:'英语语境',e:'English context helps us understand.'},
  {w:'English daily practice',p:'/ˈɪŋɡlɪʃ ˈdeɪli ˈpræktɪs/',z:'英语每日练习',e:'English daily practice takes ten minutes.'},
  {w:'English review',p:'/ˈɪŋɡlɪʃ rɪˈvjuː/',z:'英语复习',e:'English review is part of the plan.'},
  {w:'English progress',p:'/ˈɪŋɡlɪʃ ˈprɑːɡres/',z:'英语进步',e:'Your English progress is clear.'},
  {w:'English confidence',p:'/ˈɪŋɡlɪʃ ˈkɑːnfɪdəns/',z:'英语信心',e:'Practice builds English confidence.'},
  {w:'English ability',p:'/ˈɪŋɡlɪʃ əˈbɪləti/',z:'英语能力',e:'Reading improves English ability.'},
  {w:'English skill',p:'/ˈɪŋɡlɪʃ skɪl/',z:'英语技能',e:'Listening is an important English skill.'},
  {w:'English level',p:'/ˈɪŋɡlɪʃ ˈlevəl/',z:'英语水平',e:'Choose a list for your English level.'},
  {w:'English learner',p:'/ˈɪŋɡlɪʃ ˈlɜːrnər/',z:'英语学习者',e:'Every English learner needs practice.'},
  {w:'English teacher',p:'/ˈɪŋɡlɪʃ ˈtiːtʃər/',z:'英语老师',e:'Ask your English teacher for help.'},
  {w:'English classmate',p:'/ˈɪŋɡlɪʃ ˈklæsmeɪt/',z:'英语课同学',e:'Practice with an English classmate.'},
  {w:'English partner',p:'/ˈɪŋɡlɪʃ ˈpɑːrtnər/',z:'英语搭档',e:'Choose an English partner.'},
  {w:'English activity',p:'/ˈɪŋɡlɪʃ ækˈtɪvəti/',z:'英语活动',e:'The English activity was fun.'},
  {w:'English game',p:'/ˈɪŋɡlɪʃ ɡeɪm/',z:'英语游戏',e:'We played an English game.'},
  {w:'English question',p:'/ˈɪŋɡlɪʃ ˈkwestʃən/',z:'英语问题',e:'Ask an English question.'},
  {w:'English answer',p:'/ˈɪŋɡlɪʃ ˈænsər/',z:'英语答案',e:'Write an English answer.'},
  {w:'English word bank',p:'/ˈɪŋɡlɪʃ wɜːrd bæŋk/',z:'英语词库',e:'Choose an English word bank.'},
  {w:'English word card',p:'/ˈɪŋɡlɪʃ wɜːrd kɑːrd/',z:'英语单词卡',e:'Tap an English word card.'},
  {w:'English audio',p:'/ˈɪŋɡlɪʃ ˈɔːdioʊ/',z:'英语音频',e:'Listen to the English audio.'},
  {w:'English sentence audio',p:'/ˈɪŋɡlɪʃ ˈsentəns ˈɔːdioʊ/',z:'英语句子音频',e:'The English sentence audio is clear.'},
  {w:'English read aloud',p:'/ˈɪŋɡlɪʃ riːd əˈlaʊd/',z:'英语朗读',e:'English read aloud practice is helpful.'},
  {w:'English repeat',p:'/ˈɪŋɡlɪʃ rɪˈpiːt/',z:'英语跟读',e:'English repeat practice is simple.'},
  {w:'English speaking partner',p:'/ˈɪŋɡlɪʃ ˈspiːkɪŋ ˈpɑːrtnər/',z:'英语口语搭档',e:'An English speaking partner can help.'},
  {w:'English study time',p:'/ˈɪŋɡlɪʃ ˈstʌdi taɪm/',z:'英语学习时间',e:'Set English study time every day.'},
  {w:'English study goal',p:'/ˈɪŋɡlɪʃ ˈstʌdi ɡoʊl/',z:'英语学习目标',e:'Set one English study goal.'},
  {w:'English study plan',p:'/ˈɪŋɡlɪʃ ˈstʌdi plæn/',z:'英语学习计划',e:'The English study plan is short.'},
  {w:'English study habit',p:'/ˈɪŋɡlɪʃ ˈstʌdi ˈhæbɪt/',z:'英语学习习惯',e:'Build an English study habit.'},
  {w:'English study record',p:'/ˈɪŋɡlɪʃ ˈstʌdi ˈrekərd/',z:'英语学习记录',e:'The English study record is private.'},
  {w:'English study progress',p:'/ˈɪŋɡlɪʃ ˈstʌdi ˈprɑːɡres/',z:'英语学习进度',e:'English study progress takes time.'},
  {w:'English daily goal',p:'/ˈɪŋɡlɪʃ ˈdeɪli ɡoʊl/',z:'英语每日目标',e:'Choose an English daily goal.'},
  {w:'English daily words',p:'/ˈɪŋɡlɪʃ ˈdeɪli wɜːrdz/',z:'英语每日单词',e:'English daily words are easy to review.'},
  {w:'English first term',p:'/ˈɪŋɡlɪʃ fɜːrst tɜːrm/',z:'英语上学期',e:'This list covers English first term.'},
  {w:'English second term',p:'/ˈɪŋɡlɪʃ ˈsekənd tɜːrm/',z:'英语下学期',e:'We will add English second term later.'},
  {w:'English textbook',p:'/ˈɪŋɡlɪʃ ˈtekstbʊk/',z:'英语课本',e:'Bring the English textbook.'},
  {w:'English unit',p:'/ˈɪŋɡlɪʃ ˈjuːnɪt/',z:'英语单元',e:'Review the English unit this week.'},
  {w:'English lesson plan',p:'/ˈɪŋɡlɪʃ ˈlesən plæn/',z:'英语课时计划',e:'The English lesson plan is clear.'},
  {w:'English textbook sentence',p:'/ˈɪŋɡlɪʃ ˈtekstbʊk ˈsentəns/',z:'英语课本例句',e:'The English textbook sentence gives context.'},
  {w:'English topic',p:'/ˈɪŋɡlɪʃ ˈtɑːpɪk/',z:'英语主题',e:'The English topic is easy to discuss.'},
  {w:'English conversation',p:'/ˈɪŋɡlɪʃ ˌkɑːnvərˈseɪʃən/',z:'英语对话',e:'Practice the English conversation.'},
  {w:'English dialogue',p:'/ˈɪŋɡlɪʃ ˈdaɪəlɔːɡ/',z:'英语对话',e:'Read the English dialogue in pairs.'},
  {w:'English passage',p:'/ˈɪŋɡlɪʃ ˈpæsɪdʒ/',z:'英语短文',e:'Read the English passage twice.'},
  {w:'English paragraph',p:'/ˈɪŋɡlɪʃ ˈpærəɡræf/',z:'英语段落',e:'Underline the key English paragraph.'},
  {w:'English main idea',p:'/ˈɪŋɡlɪʃ meɪn aɪˈdiːə/',z:'英语主旨',e:'Find the English main idea.'},
  {w:'English detail',p:'/ˈɪŋɡlɪʃ ˈdiːteɪl/',z:'英语细节',e:'Look for an English detail.'},
  {w:'English question type',p:'/ˈɪŋɡlɪʃ ˈkwestʃən taɪp/',z:'英语题型',e:'Learn the English question type.'},
  {w:'English answer check',p:'/ˈɪŋɡlɪʃ ˈænsər tʃek/',z:'英语答案检查',e:'Use English answer check after trying.'},
  {w:'English mistake review',p:'/ˈɪŋɡlɪʃ mɪˈsteɪk rɪˈvjuː/',z:'英语错题复习',e:'English mistake review improves accuracy.'},
  {w:'English knowledge point',p:'/ˈɪŋɡlɪʃ ˈnɑːlɪdʒ pɔɪnt/',z:'英语知识点',e:'One English knowledge point is enough today.'},
  {w:'English learning loop',p:'/ˈɪŋɡlɪʃ ˈlɜːrnɪŋ luːp/',z:'英语学习循环',e:'The English learning loop is simple.'},
  {w:'English mastery',p:'/ˈɪŋɡlɪʃ ˈmæstəri/',z:'英语掌握',e:'English mastery comes from practice.'},
  {w:'English review list',p:'/ˈɪŋɡlɪʃ rɪˈvjuː lɪst/',z:'英语复习列表',e:'The English review list shows difficult words.'},
  {w:'English favorite',p:'/ˈɪŋɡlɪʃ ˈfeɪvərɪt/',z:'英语收藏词',e:'Save an English favorite.'},
  {w:'English custom list',p:'/ˈɪŋɡlɪʃ ˈkʌstəm lɪst/',z:'英语自定义词表',e:'Make an English custom list.'},
  {w:'English word note',p:'/ˈɪŋɡlɪʃ wɜːrd noʊt/',z:'英语单词笔记',e:'Write an English word note.'},
  {w:'English memory hint',p:'/ˈɪŋɡlɪʃ ˈmeməri hɪnt/',z:'英语记忆提示',e:'Add an English memory hint.'},
  {w:'English sentence pattern',p:'/ˈɪŋɡlɪʃ ˈsentəns ˈpætərn/',z:'英语句型',e:'Learn the English sentence pattern.'},
  {w:'English word family',p:'/ˈɪŋɡlɪʃ wɜːrd ˈfæməli/',z:'英语词族',e:'The English word family is useful.'},
  {w:'English collocation',p:'/ˈɪŋɡlɪʃ ˌkɑːləˈkeɪʃən/',z:'英语搭配',e:'Learn the English collocation.'},
  {w:'English part of speech',p:'/ˈɪŋɡlɪʃ pɑːrt əv spiːtʃ/',z:'英语词性',e:'Check the English part of speech.'},
  {w:'English usage',p:'/ˈɪŋɡlɪʃ ˈjuːsɪdʒ/',z:'英语用法',e:'The example shows English usage.'},
  {w:'English definition',p:'/ˈɪŋɡlɪʃ ˌdefəˈnɪʃən/',z:'英语定义',e:'Read the English definition.'},
  {w:'English translation',p:'/ˈɪŋɡlɪʃ trænzˈleɪʃən/',z:'英语翻译',e:'Compare the English translation.'},
  {w:'English context sentence',p:'/ˈɪŋɡlɪʃ ˈkɑːntekst ˈsentəns/',z:'英语语境例句',e:'The English context sentence is clear.'},
  {w:'English reading context',p:'/ˈɪŋɡlɪʃ ˈriːdɪŋ ˈkɑːntekst/',z:'英语阅读语境',e:'English reading context helps memory.'},
  {w:'English speaking context',p:'/ˈɪŋɡlɪʃ ˈspiːkɪŋ ˈkɑːntekst/',z:'英语口语语境',e:'English speaking context makes phrases useful.'},
  {w:'English listening practice',p:'/ˈɪŋɡlɪʃ ˈlɪsənɪŋ ˈpræktɪs/',z:'英语听力练习',e:'English listening practice is short.'},
  {w:'English speaking practice',p:'/ˈɪŋɡlɪʃ ˈspiːkɪŋ ˈpræktɪs/',z:'英语口语练习',e:'English speaking practice builds confidence.'},
  {w:'English reading practice',p:'/ˈɪŋɡlɪʃ ˈriːdɪŋ ˈpræktɪs/',z:'英语阅读练习',e:'English reading practice grows vocabulary.'},
  {w:'English writing practice',p:'/ˈɪŋɡlɪʃ ˈraɪtɪŋ ˈpræktɪs/',z:'英语写作练习',e:'English writing practice uses sentences.'},
  {w:'English grammar point',p:'/ˈɪŋɡlɪʃ ˈɡræmər pɔɪnt/',z:'英语语法点',e:'The English grammar point is important.'},
  {w:'English word meaning',p:'/ˈɪŋɡlɪʃ wɜːrd ˈmiːnɪŋ/',z:'英语单词含义',e:'Check the English word meaning.'},
  {w:'English word pronunciation',p:'/ˈɪŋɡlɪʃ wɜːrd prəˌnʌnsiˈeɪʃən/',z:'英语单词发音',e:'Listen to English word pronunciation.'},
  {w:'English example sentence',p:'/ˈɪŋɡlɪʃ ɪɡˈzæmpəl ˈsentəns/',z:'英语例句',e:'Read the English example sentence.'},
  {w:'English word card',p:'/ˈɪŋɡlɪʃ wɜːrd kɑːrd/',z:'英语单词卡',e:'Tap the English word card.'},
  {w:'English audio button',p:'/ˈɪŋɡlɪʃ ˈɔːdioʊ ˈbʌtən/',z:'英语音频按钮',e:'Tap the English audio button.'},
  {w:'English read and repeat',p:'/ˈɪŋɡlɪʃ riːd ænd rɪˈpiːt/',z:'英语读并重复',e:'Use English read and repeat practice.'},
  {w:'English daily review',p:'/ˈɪŋɡlɪʃ ˈdeɪli rɪˈvjuː/',z:'英语每日复习',e:'English daily review takes ten minutes.'},
  {w:'English weekly review',p:'/ˈɪŋɡlɪʃ ˈwiːkli rɪˈvjuː/',z:'英语每周复习',e:'English weekly review covers the unit.'},
  {w:'English study session',p:'/ˈɪŋɡlɪʃ ˈstʌdi ˈseʃən/',z:'英语学习时段',e:'The English study session is short.'},
  {w:'English study timer',p:'/ˈɪŋɡlɪʃ ˈstʌdi ˈtaɪmər/',z:'英语学习计时器',e:'The English study timer helps focus.'},
  {w:'English completion',p:'/ˈɪŋɡlɪʃ kəmˈpliːʃən/',z:'英语学习完成',e:'English completion is shown at the end.'},
  {w:'English learning record',p:'/ˈɪŋɡlɪʃ ˈlɜːrnɪŋ ˈrekərd/',z:'英语学习记录',e:'The English learning record is private.'},
  {w:'English progress bar',p:'/ˈɪŋɡlɪʃ ˈprɑːɡres bɑːr/',z:'英语进度条',e:'The English progress bar moves as you learn.'},
  {w:'English account',p:'/ˈɪŋɡlɪʃ əˈkaʊnt/',z:'英语学习账号',e:'The English account stores progress.'},
  {w:'English profile',p:'/ˈɪŋɡlɪʃ ˈproʊfaɪl/',z:'英语学习资料',e:'The English profile has its own list.'},
  {w:'English grade eight',p:'/ˈɪŋɡlɪʃ ɡreɪd eɪt/',z:'八年级英语',e:'This is an English grade eight list.'},
  {w:'English first semester',p:'/ˈɪŋɡlɪʃ fɜːrst səˈmestər/',z:'八年级上册英语',e:'This is English first semester practice.'},
  {w:'English Unit One',p:'/ˈɪŋɡlɪʃ ˈjuːnɪt wʌn/',z:'英语第一单元',e:'Start with English Unit One.'},
  {w:'English Unit Two',p:'/ˈɪŋɡlɪʃ ˈjuːnɪt tuː/',z:'英语第二单元',e:'English Unit Two reviews habits.'},
  {w:'English Unit Three',p:'/ˈɪŋɡlɪʃ ˈjuːnɪt θriː/',z:'英语第三单元',e:'English Unit Three compares friends.'},
  {w:'English Unit Four',p:'/ˈɪŋɡlɪʃ ˈjuːnɪt fɔːr/',z:'英语第四单元',e:'English Unit Four compares services.'},
  {w:'English Unit Five',p:'/ˈɪŋɡlɪʃ ˈjuːnɪt faɪv/',z:'英语第五单元',e:'English Unit Five discusses shows.'},
  {w:'English Unit Six',p:'/ˈɪŋɡlɪʃ ˈjuːnɪt sɪks/',z:'英语第六单元',e:'English Unit Six talks about plans.'}
];

// 先保留第一版可直接学习的 180 个不重复词条，后续按实际课本逐条校准。
GRADE8_TERM1_EXTRA = GRADE8_TERM1_EXTRA.filter(function(item, index, items) {
  return items.findIndex(function(candidate) {
    return candidate.w.toLowerCase() === item.w.toLowerCase();
  }) === index;
}).slice(0, 180);

if (typeof module !== 'undefined') module.exports = GRADE8_TERM1_EXTRA;
